### PR TITLE
7.0 hr experience

### PR DESCRIPTION
**Pull request by bwrsandman**
Port of https://code.launchpad.net/~savoirfairelinux-openerp/openerp-hr/7.0-experience/+merge/195315

### CODE REVIEW

**Comment by pedrobaeza** [comment]
LGTM

:+1: (code review)

Could you please rebase to make only one commit when merging?

**Comment by max3903** [comment]
:+1:

**Comment by bwrsandman** [comment]
@pedrobaeza done, but only because the authorship was messed up. I don't really see the point of squashing the commits.

**Comment by pedrobaeza** [comment]
Well, it's to avoid a lot of intermediate commits that doesn't apport nothing to the history. Take a look to this article about a disertation of this topic:

http://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/

Thanks for the changes.

**Comment by bwrsandman** [comment]
@pedrobaeza if you do `git log --graph` that problem goes away, there will always be a merge commit on github. The mainline should be only merges, and the branches can have as many commits as they need.

Rebasing is worse than merging if you code is public.

**Comment by pedrobaeza** [comment]
Ahm, OK, I'm still a git novice, I'm reading things like the previous blog make me think that this is one problem. I have to continue experimenting...

**Pull request merged**
