### PR TITLE
add hr accident at work 

### PR DESCRIPTION
**Pull request by EBII**

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Why not to integrate this with the already existing leaves functionality?

**Review by gurneyalex — CHANGES_REQUESTED** [review]
I like the idea. 

Can you rename your branch to 10.0-accident_at_work (the prefix is used by runbot to find the odoo version). 

Then there are some flake8 issues: https://travis-ci.org/OCA/hr/jobs/280882487#L713

**Comment by EBII** [comment]
mv 10.0 mig hr holidays validity date #370

**Comment by EBII** [comment]
mv [ADD] 10.0 accident at work #371

**Pull request closed without merging**
