### PR TITLE
[MIG] hr_employee_partner_external: Migration to 13.0

### PR DESCRIPTION
**Pull request by etobella**
Standard migration

### CODE REVIEW

**Comment by etobella** [comment]
@mymage

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Review by albariera — APPROVED** [review]

**Comment by mymage** [comment]
> @mymage

@etobella sorry but I didn't receive the notification. I hope to react faster next time.

**Comment by etobella** [comment]
Sure @mymage As original creator of the module, your comments and review will be awesome :wink:

**Pull request merged**
