### PR TITLE
[11.0][add] hr_calendar_rest_time:   Adds rest time to the calendar attendance records

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This PR adds to new modules:
- hr_calendar_rest_time: Adds rest time to the calendar attendance records
- resource_hook: Extends the resource with hooks to standard methods

The 'resource_hook' method is a dependency in hr_calendar_rest_time

HR Calendar Rest Time
==================
This module allows to add rest time to the resource calendar, to be considered
during the computation of worked hours.

For example, monday employees start at 9AM and leave at 6PM, with a rest time
of 1 hour. Therefore the time worked is 8 hours.

The correct working hours will then be correctly considered in various
existing hr reports.

Usage
=====

* As an admin user, go to 'Settings' and activate the developer mode.
* Go to to 'Settings / Technical / Resource / Working Time'.
* Add the rest time to the calendar lines, as needed.

Resource Hook
=============
This module includes additional hooks to the standard resource methods,
so that it is possible to alter the behaviour of methods, where inheritance
is not an option.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc  @etobella @jarroyomorales @aheficent

**Review by AaronHForgeFlow — COMMENTED** [review]
LGTM. Perhaps we can add a constraint to prevent setting a rest time longer than the working hours.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Review by jarroyomorales — APPROVED** [review]
:+1:

**Review by Jortolsa-S73 — APPROVED** [review]

**Review by Abranes — APPROVED** [review]

**Comment by etobella** [comment]
@jbeficent This is ready to merge :smile:

**Comment by jarroyomorales** [comment]
ping @jbeficent

**Comment by etobella** [comment]
@OCA/human-resources-maintainers I think this is ready to merge

**Pull request merged**
