### PR TITLE
[16.0][MIG] hr_employee_id: Migration to 16.0

### PR DESCRIPTION
**Pull request by maisim**
- Updated the fields syntax in hr_employee_id/views/hr_employee_views.xml
- Updated the create method in models/hr_employee.py to not break batch mode create
- Add test : test_generate_identification_id_exception

To replace https://github.com/OCA/hr/pull/1340 wich seems stuck

### CODE REVIEW

**Comment by maisim** [comment]
ping @OCA/human-resources-maintainers

**Comment by maisim** [comment]
Hi @alexey-pelykh !
Any way to get this unlocked ?

**Comment by alexey-pelykh** [comment]
@maisim you should do the migration commits as in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0 and do the improvements separately. As for #1340 - I'll follow the @pedrobaeza's lead here

**Comment by maisim** [comment]
Hi @alexey-pelykh @pedrobaeza 

I separated my changes into different commits.
However, they are all necessary for 16.0 to be happy. So, in my opinion, they have their place in the migration PR.
I hope it suits you like that.

**Comment by pedrobaeza** [comment]
There's no answer in the other PR, so let's use this one.

/ocabot migration hr_employee_id

**Comment by maisim** [comment]
:hand:  @gurneyalex @nimarosa @Saran440 
I see you have done a review for previous migrations of this module, could you take a look at it here? Thanks! :kissing:

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
/ocabot merge nobump

Functional test okay in runnoat. Code looks good too.

**Pull request merged**
