### PR TITLE
14.0 mig hr org chart overview

### PR DESCRIPTION
**Pull request by irfani**
Add custom qweb template to properly show Org Chart in Odoo V14

### CODE REVIEW

**Comment by Saran440** [comment]
@irfani Hi. 
Could you squash commit into 1, please?
Capture

**Comment by aphon61bank** [comment]
test in v14 ,It's not error.
Selection_011

**Comment by etobella** [comment]
@irfani Can you reorganize the commits as asked by @Saran440 please?

**Comment by irfani** [comment]
@Saran440 @etobella  Squash done, please check

**Review by aphon61bank — APPROVED** [review]
Test in v14 ,It not error.

**Review by etobella — APPROVED** [review]
Tested and LGTM

**Pull request merged**
