### PR TITLE
[12.0][IMP] hr_holidays_credit: add unit in form selection widget & plurals management

### PR DESCRIPTION
**Pull request by maisim**
[IMP] hr_holidays_credit: add unit in form selection widget and  plurals management

### CODE REVIEW

**Comment by maisim** [comment]
Hi @OCA/human-resources-maintainers !

Can someone have a look ? Thanks a lot !

**Comment by alexey-pelykh** [comment]
@maisim please split the commits if they are imp and fix, and name them correctly as per guidelines

**Comment by maisim** [comment]
Hi @alexey-pelykh,

Thanks for your feedback.
In this case let's say it's just an improvement :D

It's a rebasing of this old one https://github.com/OCA/hr/pull/1002  that fell into oblivion

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Please also do the forward-porting where applicable.

**Pull request merged**
