### PR TITLE
[13.0] [IMP] hr_course

### PR DESCRIPTION
**Pull request by etobella**
Finishes #1039 

@FernandoRomera

### CODE REVIEW

**Review by FernandoRomera — APPROVED** [review]

**Review by AntoniRomera — APPROVED** [review]

**Review by olgamarcocb — APPROVED** [review]
:+1:

**Comment by etobella** [comment]
@Saran440 All comments have been attended :wink:

**Comment by FernandoRomera** [comment]
@OCA/human-resources-maintainers

**Comment by Saran440** [comment]
@pedrobaeza I don't know why I can't merge on hr repo. Could you merge?

**Comment by etobella** [comment]
All members of hr have been lost

**Comment by pedrobaeza** [comment]
Please try again now. There was a problem yesterday with the bot token.

**Comment by Saran440** [comment]
Okay, It's work already, Thank you :)

**Comment by pedrobaeza** [comment]
I suppose this should be passed to v14 as well, isn't it?

**Pull request merged**
