### PR TITLE
[MIG] hr_employee_firstname: Migration to 16.0

### PR DESCRIPTION
**Pull request by luistorresm**

### CODE REVIEW

**Comment by moylop260** [comment]
👍

**Review by moylop260 — APPROVED** [review]
👍

**Review by hugho-ad — APPROVED** [review]

**Comment by moylop260** [comment]
Unittests passing well and tested functionally:
 - Screenshot 2022-11-04 at 18 59 27


So, I think we can merge it

**Review by nimarosa — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
I think ocabot had some issue here...

/ocabot merge nobump

**Pull request merged**
