### PR TITLE
[17.0][MIG] hr_holidays_settings : Migration to 17.0 

### PR DESCRIPTION
**Pull request by peluko00**

### CODE REVIEW

**Comment by peluko00** [comment]
Module migrated to version 17.0

cc https://github.com/APSL 148513

@miquelalzanillas @lbarry-apsl @javierobcn @samoros1 please review

Issue https://github.com/OCA/hr/issues/1291

**Comment by samoros1** [comment]
Functionally reviewed and working as expected!

**Comment by pedrobaeza** [comment]
@samoros1 please use proper review mechanism in GitHub for giving your approval.

**Review by samoros1 — APPROVED** [review]
Reviewed. Functionally working as expected.

**Review by samoros1 — APPROVED** [review]
Reviewed. Functionally working as expected.

**Review by lbarry-apsl — APPROVED** [review]
Validated functionality

**Comment by pedrobaeza** [comment]
Although there's no separation in the commits, let's go being very straight-forward:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
This module was incorrectly merged here, while it should be in OCA/hr-holidays, which has been migrated following other path: https://github.com/OCA/hr-holidays/tree/17.0/hr_holidays_settings

We will remove it in a PR. cc @JordiBForgeFlow

**Comment by JordiBForgeFlow** [comment]
OK!

**Pull request merged**
