### PR TITLE
[17.0][MIG] hr_course: Migration to 17.0

### PR DESCRIPTION
**Pull request by manishkumarbohra**
Module Name : HR Course (hr_course)

Migration to 17.0

For Issue #1291

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash latest 3 commits together.

/ocabot migration hr_course

**Comment by Michelle-RiveroM** [comment]
Hi @manishkumarbohra When do you think you have properly squashed the latest 3 commits together?

**Comment by Michelle-RiveroM** [comment]
@pedrobaeza what do you think is missing to do merge on this module app_hr_course?

**Comment by pedrobaeza** [comment]
- My comment about squashing
- Reviews: https://odoo-community.org/page/review - https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

**Comment by Michelle-RiveroM** [comment]
@manishkumarbohra would you do squash? follow a proposal to @pedrobaeza ?

**Pull request closed without merging**
