### PR TITLE
[10.0][FIX] replace not existing groups

### PR DESCRIPTION
**Pull request by i-vyshnevska**
replace group on correct, but haven't check this effect in each module

### CODE REVIEW

**Comment by i-vyshnevska** [comment]
@pedrobaeza 
build on master broken, have some try to fix it?

**Comment by pedrobaeza** [comment]
There should be an error with the massive change you have made.

**Comment by i-vyshnevska** [comment]
> There should be an error with the massive change you have made.

no, I have other PR with new unrelated module and get same error https://github.com/OCA/hr/pull/561

**Comment by pedrobaeza** [comment]
OK, then if main 10.0 branch is red, it's due to any change on upstream or an incorrect merge, but @OCA/human-resources-maintainers should fix it, or yourself if you are able to.

**Comment by i-vyshnevska** [comment]
reviews are welcome @simahawk @sebalix @mpanarin

**Review by simahawk — APPROVED** [review]
LG

**Pull request merged**
