### PR TITLE
[17.0][MIG] hr_course: Migration to 17.0

### PR DESCRIPTION
**Pull request by DorianMAG**
supersedes https://github.com/OCA/hr/pull/1306

### CODE REVIEW

**Review by gaelTorrecillas — APPROVED** [review]

**Review by flotho — CHANGES_REQUESTED** [review]
thanks @DorianMAG , looks like it's no more possible to add attendees in session.
this line seems to be responsible https://github.com/OCA/hr/pull/1367/files#diff-62b3dcbd5bf33b0a29e9a3c017fa5b24dcc1fb9cfffbd2e28af9582e8599a7d1R55

could you have a look ?

**Comment by DorianMAG** [comment]
> thanks @DorianMAG , looks like it's no more possible to add attendees in session. this line seems to be responsible https://github.com/OCA/hr/pull/1367/files#diff-62b3dcbd5bf33b0a29e9a3c017fa5b24dcc1fb9cfffbd2e28af9582e8599a7d1R55
> 
> could you have a look ?

Thx for the review,
it's now fix
Regards

**Review by flotho — APPROVED** [review]
functionnal test on runboat
LGTM

**Comment by flotho** [comment]
hi @OCA/human-resources-maintainers any chance to have a merge here ?

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration hr_course
/ocabot merge nobump

**Pull request merged**
