### PR TITLE
[FIX] hr_expense_invoice: unable to reconcile moves

### PR DESCRIPTION
**Pull request by cubells**
Fix two bugs:
* incorrect field
* incorrect filter for moves to reconcile.

cc @Tecnativa

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please @cubells review travis is :red_circle:

**Comment by AaronHForgeFlow** [comment]
The problem is in another module hr_period, I am creating the PR with the fix as soon as possible

**Review by pedrobaeza — APPROVED** [review]
We can fast-track this as obvious

**Comment by cubells** [comment]
@aheficent  Thank you!

**Comment by AaronHForgeFlow** [comment]
Thank you!

**Comment by pedrobaeza** [comment]
Well, the error is still there, hehe, but it's for not having another PR blocked.

**Comment by AaronHForgeFlow** [comment]
The intention is what counts :laughing:

**Pull request merged**
