### PR TITLE
[MIG][10.0] hr_period

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Supersedes #368

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@feketemihai The feature to close the current fiscal year is not implemented yet. Maybe it's enough to close the related periods, then update the contract and maybe cancel the payslips that are not done?

**Comment by feketemihai** [comment]
@aheficent Can you add it in the roadmap, to know about it, please.

**Comment by feketemihai** [comment]
@aheficent Need some more tests to be mergeable...

**Comment by AaronHForgeFlow** [comment]
This will be green eventually :smile:

**Comment by AaronHForgeFlow** [comment]
The module does not depend on payroll_account so no journal_id is added to the contract in the test. However travis is installing hr_payroll_account and failing for that reason. The bad thing is, if I add the journal to the contract in the tests then it fails because "contract has not attribute journal_id" :confused: 

Any ideas?

**Comment by feketemihai** [comment]
@aheficent Please exclude hr_payroll_cancel from your branch unit tests like this:
https://github.com/OCA/vertical-ngo/blob/11.0/.travis.yml
we will see how it behaves if merged, or you could try to adapt test and search if hr_payroll_account is installed and add update journal_id with the first miscealeanous journal

**Comment by AaronHForgeFlow** [comment]
Now it's failing because of some tests at hr_holidays_validity_date, which is overlapping leaves dates. Has anyone proposed a solution for this?

**Comment by feketemihai** [comment]
In #370

**Comment by AaronHForgeFlow** [comment]
Thanks!

**Comment by feketemihai** [comment]
@aheficent Can you rebase agains 10.0 branch to have the fix for validity dates and squash commits.

**Comment by feketemihai** [comment]
@aheficent Can you check please why the onchange on payslip is not working, if you launch from batches it's ok, but individual pyslip the onchange is not working, and default search on period,

**Comment by AaronHForgeFlow** [comment]
@feketemihai sure I'll check

**Comment by AaronHForgeFlow** [comment]
@feketemihai I can't see what you mean on the default_search for hr_period. The name of the period contains the fiscal year name and the period number and I can search by both parameters. Isn't that ok?

**Comment by feketemihai** [comment]
@aheficent when i created a new payslip, not through batched, it didn't assigned a default value to period, even that the period was open, i will recheck when runbot will be build again.

**Review by feketemihai — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
@eficent

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
