### PR TITLE
[14.0][MIG] hr_contract_multi_job

### PR DESCRIPTION
**Pull request by aphon61bank**
Standard Migration, Ready for review.

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Comment by aphon61bank** [comment]
@tonygalmiche thank you for review.

**Comment by Saran440** [comment]
Please, Squash your PR into 2 commit.

**Comment by aphon61bank** [comment]
@Saran440 I'm edit commit finish. Thank you for review.

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Comment by newtratip** [comment]
@Saran440, Could you review/approve this ?

**Pull request merged**
