### PR TITLE
[12.0][MIG] hr_holidays_leave_auto_approve

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM

**Comment by alexey-pelykh** [comment]
@astripe please enhance test coverage

**Comment by alexey-pelykh** [comment]
Also, to avoid junk in history, squash the commits into one

**Comment by nikul-serpentcs** [comment]
@astirpe README [using](https://github.com/OCA/maintainer-tools/tree/master/template/module/readme)

**Comment by astirpe** [comment]
@nikul-serpentcs the readme will be generated automatically

**Comment by nikul-serpentcs** [comment]
> @nikul-serpentcs the readme will be generated automatically

Yes, But If generated that good.

**Review by tarteo — APPROVED** [review]
LGTM

**Comment by tafaRU** [comment]
@astirpe could you please squash last two commits to only one?

**Comment by astirpe** [comment]
Squashed. Thanks!

**Pull request merged**
