### PR TITLE
[16.0][FIX]only create and unlink necessary resource_calendar_leaves

### PR DESCRIPTION
**Pull request by ChristophAbenthungCibex**
Only the necessary resource.calendar.leaves will be changed. 
This prevents the incorrect behavior described in the issue: https://github.com/odoo/odoo/issues/138580

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Thanks for the PR. Seems OK. Please name the commit message properly https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

**Comment by ChristophAbenthungCibex** [comment]
> Thanks for the PR. Seems OK. Please name the commit message properly https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

Done. Hope its better now

**Review by pedrobaeza — APPROVED** [review]
Please remove `[16.0]` from the commit message. The version is only put on the PR title, not on the commit message.

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
