### PR TITLE
[12.0][FIX] hr_holidays_accrual_advanced: tests and more logs

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza please fast-track if possible. Changes made:
 * one test input params changed since if 1 day delta is likely to be on weekend, so tests are failing 3 days in a week out of 7
 * Added more logs about how calculation is happening
 * Moved one code block a bit lower to have data to put to log - does not affect the calculation

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I prefer to not have that logs always hammering while only needed by debugging purposes. Put them under `debug` level or remove them at all.

**Comment by alexey-pelykh** [comment]
@pedrobaeza replaced all except one with `debug`

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I still think it's too much code added for only maintaining some kind of debug information...

**Pull request closed without merging**
