### PR TITLE
[14.0][MIG] hr_employee_ppe

### PR DESCRIPTION
**Pull request by AntoniRomera**

### CODE REVIEW

**Comment by AntoniRomera** [comment]
@OCA/human-resources-maintainers

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Review by albariera — APPROVED** [review]
Functional review LGTM :+1:

**Review by FernandoRomera — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@OCA/human-resources-maintainers  Anyone can merge?

**Pull request merged**
