### PR TITLE
7.0 - Improve hr_activity_on_timesheet widget

### PR DESCRIPTION
**Pull request by ghost**
This commit improves the timesheet widget of hr_activity_on_timesheet. Adding a line in the widget is faster and more user friendly. Instead of choosing the account, clicking on next and then choosing the activity, the 2 fields will now appear side by side. When the account is selected, the first activity available for this account is automatically selected. If an activity was already selected before and is still available, the same activity is kept.

### CODE REVIEW

**Comment by max3903** [comment]
:+1:

**Comment by mdietrichc2c** [comment]
Code review, LGTM :+1: ( @charbeljc , can you validate on the runbot?)

**Comment by ghost** [comment]
@bwrsandman I would like your review here.

**Comment by bwrsandman** [comment]
LGTM :+1: A runbot review would be nice

**Comment by mdietrichc2c** [comment]
Just validated it on Runbot. :+1:

**Pull request merged**
