### PR TITLE
[13.0][FIX] hr_employee_calendar_planning: Prevent inconsistent company + Avoid create employees without calendar planing.

### PR DESCRIPTION
**Pull request by victoralmau**
Prevent inconsistent company + Avoid create employees without calendar planing.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT35897

### CODE REVIEW

**Comment by victoralmau** [comment]
Ping @pedrobaeza , I think these changes are necessary when employee does not have a defined company.

**Review by pedrobaeza — APPROVED** [review]

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Pull request merged**
