### PR TITLE
[13.0][IMP] hr_employee_firstname: ease extension

### PR DESCRIPTION
**Pull request by astirpe**
This allows module `hr_employee_firstname` to be extended in an easier way.
See https://github.com/OCA/hr/pull/877 as a possible example of use.

### CODE REVIEW

**Review by Saran440 — APPROVED** [review]
Functional Test. No major change.

**Review by hugho-ad — APPROVED** [review]

**Comment by hugho-ad** [comment]
LGTM
:+1: 

@moylop260 @lescobarvx we should backport this

**Review by moylop260 — APPROVED** [review]
👍

**Pull request merged**
