### PR TITLE
[17.0][MIG] hr_employee_relative: Migration to 17.0

### PR DESCRIPTION
**Pull request by ppyczko**

### CODE REVIEW

**Comment by ppyczko** [comment]
Module migrated to version 17.0

cc https://github.com/APSL 158255

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @BernatObrador please review

Issue https://github.com/OCA/hr/issues/1291

**Review by peluko00 — APPROVED** [review]
LGTM, code review and tested in runboat

**Review by mpascuall — APPROVED** [review]
LGTM

**Review by BernatObrador — APPROVED** [review]
LGTM, code review and tested in runboat

**Comment by andres-pcg** [comment]
Hey @pedrobaeza by any chance, do you know who is the maintainer or can you please help us out with this merge?

Thanks in advance. 

Regards,

**Comment by pedrobaeza** [comment]
@Saran440 may help. I see controversial to strip the years float field to integer.

**Comment by andres-pcg** [comment]
Thanks you! @pedrobaeza .

@Saran440 your feedback is really important and welcomed here. So this PR can be merge. Thanks.

**Comment by Saran440** [comment]
@andrp92 I think we should add separate fields to store `age_year`, `age_month`, and `age_day` to capture all details.
This way, we can accommodate any projects or countries that might require age in terms of months or days. (allow invisible it if not need)

What do you think?


However, I tested this module and it worked. :+1:

**Review by Saran440 — APPROVED** [review]

**Comment by andres-pcg** [comment]
@Saran440 It sounds reasonable. However, please notice that it was already managed in a single field back in:
- 15.0 https://github.com/OCA/hr/blob/15.0/hr_employee_relative/models/hr_employee_relative.py#L40
- 16.0 https://github.com/OCA/hr/blob/16.0/hr_employee_relative/models/hr_employee_relative.py#L37. 

But yes, I think that can be improved. What do you think @ppyczko?

**Comment by ppyczko** [comment]
@Saran440 @andrp92 thank you for your feedback! I added the requested changes, let me know if there's anything else!

**Comment by Saran440** [comment]
@ppyczko Could you split commit
1. [MIG] --> for standard migration
2. [ENH] --> for enhance field float to integer. we will can backport this commit.

**Comment by ppyczko** [comment]
@Saran440 done, thanks!

**Pull request merged**
