### PR TITLE
[18.0][MIG] hr_employee_second_lastname: Migration to 18.0

### PR DESCRIPTION
**Pull request by edy1192**

### CODE REVIEW

**Comment by edy1192** [comment]
Hi @luisg123v @luistorresm @andreagidaltig could you check this, please?

Regards.

**Review by luistorresm — APPROVED** [review]
Thanks @edy1192

**Comment by andreagidaltig** [comment]
> Hi @luisg123v @luistorresm @andreagidaltig could you check this, please?
> 
> Regards.

LGTM :+1:

**Comment by edy1192** [comment]
Hi @luisg123v could you check this, please?

**Review by luisg123v — APPROVED** [review]
LGTM :+1: 

@moylop260 could you review/merge, please?

Remember to run the command to mark this as a migration PR.

**Pull request merged**
