### PR TITLE
13.0 mig hr attendance report theoretical time

### PR DESCRIPTION
**Pull request by pegonzalezspesol**
Work in progress.. just did run the pre-commit

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please move this to OCA/hr-attendance following #732?

**Comment by pegonzalezspesol** [comment]
> Can you please move this to OCA/hr-attendance following #732?

Pedro, if I do a standard move the history of commits will disappear. Is there a way to preserve this in case of repository migration?. Any doc about this topic?. Thanks

**Comment by pedrobaeza** [comment]
You just have to use the same command as for migrating history, but having 2 remotes. In a nutshell:
```
git remote add pegonzalezspesol git@github.com:pegonzalezspesol/hr.git
git remote add hr-attendance git@github.com:OCA/hr-attendance.git
git fetch --all
git format-patch --keep-subject --stdout origin/13.0..pegonzalezspesol/13.0-mig-hr_attendance_report_theoretical_time -- hr_attendance_report_theoretical_time | git am -3 --keep
```

**Comment by pedrobaeza** [comment]
And check why is everything red

**Comment by pegonzalezspesol** [comment]
@pedrobaeza success on moving and keeping the history on hr-attendance repository. Now in the process of doing the tests working 

https://github.com/OCA/hr-attendance/pull/1

Feel free to close this one

**Comment by pedrobaeza** [comment]
Great, thanks.

**Pull request closed without merging**
