### PR TITLE
[MIG] gamification_badge_report : Migrated to 13.0.

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@pedrobaeza

**Comment by AmmarOfficewalaSerpentCS** [comment]
@marcelsavegnago and @dreispt ,

can you please review this PR?

**Review by olgamarcocb — APPROVED** [review]
LGTM 👍

**Review by dreispt — APPROVED** [review]

**Pull request merged**
