### PR TITLE
[10.0][FIX] hr_holidays_validity_date: fix tests conflicts

### PR DESCRIPTION
**Pull request by astirpe**
Fix tests + fix category + fix indentation

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you rebase after the merges I have made?

**Comment by astirpe** [comment]
Rebased!

**Comment by astirpe** [comment]
Ops not yet, sorry ...

**Comment by astirpe** [comment]
Tests need extra effort to be fixed ...

**Comment by astirpe** [comment]
I close this PR since the tests are actually passing in branch 10.0

**Pull request closed without merging**
