### PR TITLE
[12.0][FIX] hr_holidays_leave_request_wizard: used fields must be in XML

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Workarounds https://github.com/odoo/odoo/issues/35419

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think you are facing https://github.com/odoo/odoo/issues/20163

**Comment by alexey-pelykh** [comment]
@pedrobaeza I doubt that, since it was working when it was tested and merged couple of months ago

**Comment by pedrobaeza** [comment]
Well, I don't think this big patch is the solution either, and you are declaring incorrectly the fields in the one2many. You must put either `<tree>` or `<form>` in between. What is clear is that non nested views are a problem, so nest the views of children models.

**Comment by alexey-pelykh** [comment]
Yeah, this fix still does not fix anything :( And nested views are not pulled at all, e.g. field of one2many won't use XML declaration at all. Right now not sure how to proceed with actual fix

**Pull request closed without merging**
