### PR TITLE
[MIG] [14.0] hr_period

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
@ForgeFlow 

Adds the concept of period in the human resources management.

The objective of the module is to create periods of time to be used in the human resources management flows such as specific payroll period of time or timesheet periods.

Regarding to payrolls, it adds the date of payment on the payslip and payslip batch. This date is automatically filled when selecting a period. It also adds a sequence on the payslip batch name and the company on the payslip batch.

This module depends now on the OCA payroll module

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Funcional review ok. But I am getting an error when accessing to the HR Period menu

**Review by AaronHForgeFlow — APPROVED** [review]
Functional + code Looks good!

**Comment by AaronHForgeFlow** [comment]
Hi @JuanyDForgeflow can you remove the (WIP) from the title?

**Review by albariera — APPROVED** [review]
Code Review LGTM :+1:

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Pull request merged**
