### PR TITLE
7.0 linelength

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by dreispt** [comment]
Judging from the build log, there are still a lot of lines too long :-/

**Comment by bwrsandman** [comment]
It's a WIP, there is so much code in this repo... And I already did this for line length 120...

I think this repo needs a serious audit, some of the code I am seeing is awful...

**Comment by pedrobaeza** [comment]
Yeah, I have the same sensation...

But let's put Travis green, and then we think about it. Let me know if you need help, and we split the work.

Regards.

**Comment by bwrsandman** [comment]
@pedrobaeza issue created https://github.com/OCA/hr/issues/18

**Comment by eLBati** [comment]
Hello @bwrsandman I would like to contribute to this. I'm going to propose a PR to your branch, if you are not working on it right now

**Comment by eLBati** [comment]
Here is the first PR https://github.com/savoirfairelinux/hr/pull/1

**Comment by eLBati** [comment]
And here is the final PR https://github.com/savoirfairelinux/hr/pull/2

**Comment by bwrsandman** [comment]
@eLBati Thanks

**Comment by eLBati** [comment]
Taking the chance of the remaining aeroo error, we could add the aeroo modules to https://github.com/OCA/reporting-engine
@sraps would you be interested?
Is OCA  interested?

**Comment by pedrobaeza** [comment]
:+1: for PEP8. Travis configuration must be updated for having OCB also.

**Comment by sraps** [comment]
- I am not sure about all of the comments about lines being too long, moreover new PEP are planned with longer lines as a standard.
- What about Aeroo Reports, I am planning to move all the code from launchpad to git, eventually. And would prefer having all the Aeroo stuff under one roof. After implementing new conversion engine for Aeroo on Odoo v8, I plan to backport it to v7. As there's not so many changes in OpenERP Aeroo modules in itself.

**Comment by eLBati** [comment]
Hello @sraps, the main question is summarized as: are you interested in moving aeroo modules under the OCA roof?
More info about OCA: http://odoo-community.org/

**Comment by bwrsandman** [comment]
@eLBati, @sraps can you move this discussion to another issue or perhaps the mailing list?
I would like to merge these PEP8 fixes and this discussion is unrelated.

**Comment by sraps** [comment]
I agree, the discussion is unrelated to this topic.

**Comment by rvalyi** [comment]
Wow, what a amazing amount of cleanup @bwrsandman !

:+1: LGTM, code review, no test.

Now I wonder, use are using two styles of cr.execute:

You are mostly using:

```
            cr.execute("""\
SELECT id
FROM hr_schedule
WHERE (date_start <= %s and %s <= date_end)
  AND employee_id=%s
  AND id <> %s""", (shd.date_end, shd.date_start, shd.employee_id.id, shd.id))
             if cr.fetchall():
```

But sometimes you used:

```
        self.cr.execute(
            "SELECT exp.name, exp.start_date, exp.expire, exp.end_date, "
            "exp.location, exp.certification, "
            "exp.description, exp.diploma, exp.study_field, "
            "part.name partner_name FROM hr_experience exp "
            "LEFT JOIN res_partner part ON part.id = exp.partner_id "
            "WHERE exp.employee_id = %d AND exp.category = '%s'"
            % (employee_id, category))
       return self.cr.dictfetchall()
```

I wonder, it there a style that is better than another?

**Comment by pedrobaeza** [comment]
The second one concatenates all strings instead of inserting line breaks, so you have to take care of final spaces before the end of this line string.

**Comment by eLBati** [comment]
About aeroo, just opened https://github.com/OCA/reporting-engine/issues/1
About this PR, LGTM :+1:

**Comment by dreispt** [comment]
:+1: LGTM

The server test failing is an issue.
IMO it's a "minor evil" to avoid that including Aeroo in this repos's TravisCI installed dependencies, until https://github.com/OCA/reporting-engine/issues/1 is sorted out.

**Comment by bwrsandman** [comment]
@dreispt The first style is easy to read in the code (like the second style) but the line breaks are one for one in the sql log.
The second style is nice to read in the code, but if you log the sql queries, they come out in a single line.

There is also the added benefit of allowing longer lines (since you start at column 0) and guarding against whitespace errors that you can run into with the second style if you don't pay attention:

``` python
>>> ("SELECT *"
     "FROM table")
"SELECT *FROM table"
        ^
```

**Pull request merged**
