### PR TITLE
[MIG][16.0] hr_employee_id: Migrated module.

### PR DESCRIPTION
**Pull request by Chirag-OSI**

### CODE REVIEW

**Comment by SMaciasOSI** [comment]
@max3903 @pedrobaeza I have a question. We would like to modify this module in order to use the existing field employee_number instead of the new field identification_id. To make this change, should I wait for this migration PR to be merged first and then do a new PR with the mod, or can I add the adjustments to this PR?

**Comment by pedrobaeza** [comment]
I think that should be another module, not this one.

**Comment by SMaciasOSI** [comment]
> I think that should be another module, not this one.

The functionality would be the exact same, just making use of an existing field instead of adding a new one. Both fields serve virtually the same purpose

**Comment by pedrobaeza** [comment]
But you may be using the other for another purpose. Is it a new field? Is it hidden by any reason?

**Comment by unique4** [comment]
> @max3903 @pedrobaeza I have a question. We would like to modify this module in order to use the existing field employee_number instead of the new field identification_id. To make this change, should I wait for this migration PR to be merged first and then do a new PR with the mod, or can I add the adjustments to this PR?

I do agree, since identification field is listed in Nationality info group, mean it's original purpose is for nationality identification number, not company id number. 

image

**Comment by maisim** [comment]
Hi @pedrobaeza 

It seems the build is stuck, is it possible to restart it ?

**Comment by pedrobaeza** [comment]
I can't do that. The contributor should do a push on their branch to relaunch it.

**Comment by maisim** [comment]
> It seems the build is stuck, is it possible to restart it ?
>> I can't do that. The contributor should do a push on their branch to relaunch it.

 :hand:  @Chirag-OSI

**Comment by pedrobaeza** [comment]
Superseded by #1373, as there's no answer.

**Pull request closed without merging**
