### PR TITLE
[12.0][FIX] name duplicate with module hr_expense_advance_clearing

### PR DESCRIPTION
**Pull request by Saran440**
rename field `residual` on 2 module
- hr_expense_advance_clearing - rename to `clearing_residual`
- hr_expense_payment_difference - rename to `difference_residual`

reference : https://github.com/OCA/hr/issues/955

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]
LGTM :+1:  The field is not stored so there shouldn't be any problem changing its name.

**Review by marcelsavegnago — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Have both fields the same meaning in both modules?

**Comment by Saran440** [comment]
@pedrobaeza yes
In hr_expense_advance_clearing module has `residual` field for clearing advance
https://github.com/OCA/hr/blob/12.0/hr_expense_advance_clearing/models/hr_expense_sheet.py#L29

In hr_expense_payment_difference module has `residual` field for keep amount residual on expense
https://github.com/OCA/hr/blob/12.0/hr_expense_payment_difference/models/hr_expense.py#L10

**Comment by hitrosol** [comment]
Functionally tested locally, looks good 👍

**Comment by pedrobaeza** [comment]
Then I propose to rename the hr_expense_advance_clearing to `clearing_residual` and the other to `difference_residual` and always take the guideline to not putting very generic names to fields that can collapse.

**Comment by Saran440** [comment]
@pedrobaeza fixed. rename 2 module `clearing_residual` and `difference_residual`
Thank you for your advise :)

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
