### PR TITLE
[13.0][mig] hr_attendance_autoclose

### PR DESCRIPTION
**Pull request by mondoraemon**
Working progress.

### CODE REVIEW

**Comment by jarroyomorales** [comment]
@mondoraemon This should be moved to https://github.com/OCA/hr-attendance as discussed in #732

**Comment by kittiu** [comment]
@jarroyomorales thanks!
@mondoraemon sorry, I also just know this. You need to redo the PR of this module again to OCA/hr-attendance.

**Comment by sergioliva7** [comment]
@mondoraemon This should be moved to hr-attendance. Also in v13 api.multi is not used.

**Comment by Saran440** [comment]
move on https://github.com/OCA/hr-attendance/pull/11

**Pull request closed without merging**
