### PR TITLE
[UPD] Add code to the search view department

### PR DESCRIPTION
**Pull request by ehdem**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1: Thanks! This was needed.

**Comment by bwrsandman** [comment]
Shouldn't an index for code be added if it's going to be searched heavily?

**Comment by pedrobaeza** [comment]
What about the comment about the index?

**Comment by ehdem** [comment]
@pedrobaeza : Do you know a way to add an index?

**Comment by ghost** [comment]
@ehdem in your field, you add the parameter select=True. This creates an index.

**Comment by ehdem** [comment]
@dufresnedavid : Check the doc, it is  on the Foreign Key field (in odoo7)

**Comment by ehdem** [comment]
@pedrobaeza @dufresnedavid : In Odoo8, it is index=True

**Comment by ghost** [comment]
@ehdem https://github.com/nbessi/odoo_new_api_guideline/blob/master/source/fields.rst Well, this is what it says here.

**Comment by ghost** [comment]
never mind, it is index=True in v8.

**Comment by pedrobaeza** [comment]
select=True is still allowed

**Comment by bwrsandman** [comment]
Does it create an index in the table?

**Pull request merged**
