### PR TITLE
[11.0][IMP] hr_attendance_report_theoretical_time: recompute attendances

### PR DESCRIPTION
**Pull request by jarroyomorales**
Same as https://github.com/OCA/hr/pull/718 but for 11.0

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by jarroyomorales** [comment]
I also put the new menu under the `Theoretical vs Attended Time` menu.

**Comment by pedrobaeza** [comment]
@chienandalu do you think this change is good? I'm not sure, as the idea is that only managers are able to do that operation.

**Comment by jarroyomorales** [comment]
@pedrobaeza I changed the menu position but kept the same group. Only managers can recompute.

**Comment by chienandalu** [comment]
It's ok for me. It can fit there as well

**Review by chienandalu — APPROVED** [review]
:+1: Tested on runbot and code review

**Comment by pedrobaeza** [comment]
/ocabot merge minor

Now only 12.0 is pending. @chienandalu can you?

**Pull request merged**
