### PR TITLE
port module hr_contract_init, hr_contract_state, hr_emergency_contact…

### PR DESCRIPTION
**Pull request by yweng8111**
…, hr_experience, hr_job_categories, hr_languages, hr_public_holidays, hr_security and hr_skill for odoo v9

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please, only one module per PR, and check other PRs that already migrate some of this.

**Comment by dreispt** [comment]
Hi @yweng8111, we want back the porting work you did 😄 
Please open those PRs!

**Comment by yweng8111** [comment]
Hi, @dreispt, I will try to open them again after signing the CLA. My boss have to send the ECLA at first.

**Comment by dreispt** [comment]
Good, thanks for the update!

**Pull request closed without merging**
