### PR TITLE
[ADD] hr_branch: Allow define branch on employee department

### PR DESCRIPTION
**Pull request by luistorresm**
This module allows define the company branches, and allow indicate the
employees by each one.

To allow define the employee branch, is necessary to assign the correct
branch on the department.

### CODE REVIEW

**Comment by FernandoRomera** [comment]
Do you visit https://github.com/OCA/brand ?

**Comment by luistorresm** [comment]
Hello @FernandoRomera 

This is to allow indicate the company branch in the employee department, not the brand.

Regards

**Review by moylop260 — APPROVED** [review]
👍

**Comment by hugho-ad** [comment]
LGTM :+1:

**Review by hugho-ad — APPROVED** [review]

**Comment by moylop260** [comment]
@FernandoRomera 
Do you agree with Luis Torres answer?

@astirpe @alexey-pelykh @marylla 
What do you think?

**Review by nhomar — APPROVED** [review]

**Pull request merged**
