### PR TITLE
[9.0][MIG] hr_payslip_change_state

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
* [x] Depends on #327 

Tasks done:
* Bump version.
* Rename openerp tags.
* Add icon.
* Update README and manifest.
* Squash Transifex commits.
* Adapt test.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please, rebase the PR 😉

**Comment by LoisRForgeFlow** [comment]
Done, thanks @mreficent 

Everything :green_apple: and ready to review/merge.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested on local + code review

**Pull request merged**
