### PR TITLE
[15.0][MIG] hr_employee_id

### PR DESCRIPTION
**Pull request by mtelahun**

### CODE REVIEW

**Review by Saran440 — APPROVED** [review]
Code Review, No major change :+1:

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Looks okay. 

/ocabot merge nobump

**Comment by nimarosa** [comment]
Pre-commit crashed for some reason. Lets try again.

/ocabot merge nobump

**Comment by mtelahun** [comment]
@nimarosa I think you have to copier update. I have the same problem in 
a local repo

**Comment by TheerayutEncoder** [comment]
Hi @nimarosa , @mtelahun 
I just update **hr copier v15.0**.
Can you try to merge again?
Thanks.

**Pull request merged**
