### PR TITLE
[FIX] hr_attendance_geolocation fixes kiosk mode with pin

### PR DESCRIPTION
**Pull request by cvinh**
Steps to reproduce :
Try to use in kiosk mode with PIN code
It always says "Wrong PIN"

### CODE REVIEW

**Comment by cvinh** [comment]
cc @luceeasypme

**Comment by cvinh** [comment]
cc @AdriaGForgeFlow

**Review by Saran440 — APPROVED** [review]
Functional Test, LGTM :+1:

**Review by marcelsavegnago — APPROVED** [review]
Functional Test OK

**Pull request merged**
