### PR TITLE
[14.0][MIG] hr_employee_ssn

### PR DESCRIPTION
**Pull request by aphon61bank**
Standard migration.

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Comment by aphon61bank** [comment]
Thank you for review.

**Review by jarroyomorales — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by flotho — APPROVED** [review]
tested on runbot LGTM

**Pull request merged**
