### PR TITLE
[13.0] [MIG] hr_skill

### PR DESCRIPTION
**Pull request by JevinD**
hr_skill migration from 12.0 to 13.0

### CODE REVIEW

**Comment by JevinD** [comment]
@bodedra Travis is green for this module. Core odoo also has a hr_skills but the functionality is different.

**Comment by bodedra** [comment]
Odoo v13.0 introduce "hr_skills" module which has covered most of OCA "hr_skill" module functionality. 

So IMO, OCA "hr_skill" module can be archive.

@OCA/human-resources-maintainers @dreispt @alexey-pelykh any suggestion?

**Review by tonygalmiche — APPROVED** [review]
LGTM : Code review and functional review with runbot

image

**Comment by tonygalmiche** [comment]
> Odoo v13.0 introduce "hr_skills" module which has covered most of OCA "hr_skill" module functionality. 
> So IMO, OCA "hr_skill" module can be archive.

I think it is good to leave the choice to the user and this also makes it possible to facilitate migrations for those who have used this module

However, this module seems incompatible with "hr_skills". I couldn't install "hr_skills"
```
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Field `level` does not exist
Error context:
View `hr.employee.view.form.inherit.resume`
[view_id: 500, xml_id: n/a, model: hr.employee, parent_id: 411]
```
It should perhaps be specified in  README.rst ?

**Comment by bodedra** [comment]
@tonygalmiche Thanks for your functional review. I agree with your point.

@JevinD Would you please add "excludes" key in manifest file. Here is example: https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L30

    "excludes": [
        "hr_skills",
    ],

**Comment by Saran440** [comment]
I agree with @bodedra. 
In odoo13 has covered most of this module.
we should be used core odoo or depend it to do something.

**Comment by JevinD** [comment]
> @tonygalmiche Thanks for your functional review. I agree with your point.
> 
> @JevinD Would you please add "excludes" key in manifest file. Here is example: https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L30
> 
> ```
> "excludes": [
>     "hr_skills",
> ],
> ```

I have added this to the manifest.

**Comment by JevinD** [comment]
@bodedra I have added the exclude to the manifest

**Pull request closed without merging**
