### PR TITLE
[12.0][IMP] hr_expense_cancel : Cancel vendor bills from hr_expense

### PR DESCRIPTION
**Pull request by Saran440**
Step to error:
1. create expense normal process
2. Submit to Manager > Approve > Create Vendor Bill
3. Post Journal Entries and click cancel
4. when you click cancel it will showed message error.
`You cannot do this modification on a reconciled entry. You can just change some non legal fields or you must unreconcile first.`

IMP : Collaborative support module hr_expense_cancel and hr_expense_invoice.
you can cancel when create invoice from hr_expense.

### CODE REVIEW

**Comment by Saran440** [comment]
@ps-tubtim @danhvophuong @jarroyomorales Could you please help review.

**Review by ps-tubtim — APPROVED** [review]
Code and Functional review: OK.

**Review by AaronHForgeFlow — COMMENTED** [review]
Does this work if hr_expense_invoice is not installed?

**Comment by Saran440** [comment]
@AaronHForgeFlow yes, it's work. In account move line will not has invoice_id if you not install hr_expense_invoice

**Comment by kittiu** [comment]
@AaronHForgeFlow your request is addressed?

**Review by newtratip — APPROVED** [review]
:+1: LGTM

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I don't see correct that cancelling an expense, should cancel possible linked invoices, as they can be different documents, and although linked, it belongs to different persons to process them.

**Pull request closed without merging**
