### PR TITLE
7.0 - Upgrade hr_contract_multi_jobs

### PR DESCRIPTION
**Pull request by ghost**
Module hr_contract_multi_jobs
Fix the case where a value is write in the field job_id of a contract.
This makes the module compatible with any module that does not depend on hr_contract_multi_jobs.

### CODE REVIEW

**Comment by ghost** [comment]
@max3903 This PR will prevent compatibility issues with the module hr_contract_multi_jobs in the future.

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by ghost** [comment]
@max3903 I guess we can merge this PR.

**Pull request merged**
