### PR TITLE
[16.0][MIG] hr_employee_document: Migration to 16.0.

### PR DESCRIPTION
**Pull request by BT-anieto**

### CODE REVIEW

**Comment by BT-anieto** [comment]
@pedrobaeza Created PR for hr_employee_document

**Comment by luistorresm** [comment]
Hello @BT-anieto 

Please apply this task to your MR: (You can see this [here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0))

`Squash administrative commits (if any) with the previous commit for reducing commit noise. They are named as "[UPD] README.rst", "[UPD] Update $MODULE.pot", "Update translation files" and similar names, and comes from OCA-git-bot, oca-travis or oca-transbot. IMPORTANT: Don't squash legit translation commits, authored by their translators, with the message "Translated using Weblate (...)".`

**Review by BT-nfrancisco — APPROVED** [review]

**Comment by AlbertoNieto44** [comment]
@luistorresm Hi Luis. Could you take a look at this PR?

**Review by luistorresm — APPROVED** [review]

**Comment by BT-anieto** [comment]
Why is it always building?

**Comment by victoralmau** [comment]
Please, add https://github.com/OCA/hr/pull/1271 to commit history.

**Comment by BT-anieto** [comment]
@victoralmau I'll do it asap

**Comment by BT-anieto** [comment]
@victoralmau Done!

**Review by victoralmau — APPROVED** [review]
Functional review OK.

**Pull request merged**
