### PR TITLE
[12.0][FIX] hr_expense_advance_clearing

### PR DESCRIPTION
**Pull request by kongrattapong**
fix code from issue #669
@kittiu @abdallamhafeez

### CODE REVIEW

**Review by kittiu — APPROVED** [review]

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
Hi, can this very small fix be merged?

**Review by jarroyomorales — APPROVED** [review]

**Comment by TheCloneMaster** [comment]
Hi, I just tested but it still fails when there is already expenses in the database
`    if line.account_id == emp_advance.property_account_expense_id:
AttributeError: 'NoneType' object has no attribute 'property_account_expense_id'
`
because now emp_advance is False...

**Comment by kittiu** [comment]
@TheCloneMaster thanks for your review. Yes, in deed, if hr.expense.sheet has some move line, it will error.
Now, I fixed it in another PR https://github.com/OCA/hr/pull/746 (as this PR has corrupt branch).

**Comment by kittiu** [comment]
@kongrattapong please close this PR.

**Pull request closed without merging**
