### PR TITLE
[13.0][ADD] hr_employee_firstname_middlename

### PR DESCRIPTION
**Pull request by astirpe**
This module adds the field `middle_name` to the employee's form.

See https://en.wikipedia.org/wiki/Middle_name

Depends on:

- [x] https://github.com/OCA/hr/pull/878

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Review by jarroyomorales — APPROVED** [review]
Tested on runbot and LGTM :+1:

**Comment by Saran440** [comment]
Hi @astirpe, Could you rebase this pr into 1, please?

**Comment by astirpe** [comment]
@Saran440 done, thanks!

**Comment by Saran440** [comment]
@astirpe Please, you check travis is red.
and I suggest module should name `hr_employee_middlename`. WDYT?

**Pull request closed without merging**
