### PR TITLE
[12.0][MIG] hr_course

### PR DESCRIPTION
**Pull request by jarroyomorales**
Standard migration

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Review by etobella — APPROVED** [review]
LGTM :+1: No major changes

**Comment by jarroyomorales** [comment]
@alexey-pelykh Can this be merged?

**Review by Saran440 — APPROVED** [review]
Functional Test. LGTM :+1:

**Comment by Saran440** [comment]
@jarroyomorales please, can you fix test script error?

**Comment by jarroyomorales** [comment]
@Saran440 I am not able to reproduce the error locally, can we try again and see if it works?

**Comment by jarroyomorales** [comment]
@Saran440 It worked now, I dont know why it was failing. The red is because `npm` is failing, maybe they are down or something...

**Comment by etobella** [comment]
@Saran440 The issue with npm was external. I is fixed now. Can you retry to merge again please?

**Pull request merged**
