### PR TITLE
[FIX] hr_employee_ppe: fix error when assigning multiple PPE to an employee.

### PR DESCRIPTION
**Pull request by azucenatrey**
Fix
'''
     Error while validating constraint
     Expected singleton: hr.employee.ppe(5, 6)
'''
error when assigning multiple PPE to an employee.

### CODE REVIEW

**Comment by azucenatrey** [comment]
Solution proposed for this issue: https://github.com/OCA/hr/issues/1352

**Review by marcelsavegnago — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by MiguelPoyatos — APPROVED** [review]

**Review by cubells — APPROVED** [review]
:+1: 

It's Yes for me.

**Comment by azucenatrey** [comment]
Hi @eduaparicio, @marcelsavegnago 
Please can you review this pull request to fix an error to avoid that it is marked as "no stale"? Thanks.

**Comment by marcelsavegnago** [comment]
ping @etobella @OCA/human-resources-maintainers

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
/ocabot merge patch

Can you port the change to next versions?

**Comment by azucenatrey** [comment]
Thanks!

**Pull request merged**
