### PR TITLE
[14.0][MIG] hr_employee_phone_extension

### PR DESCRIPTION
**Pull request by aphon61bank**
Standard Migration.

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot : 

image

**Comment by Saran440** [comment]
@aphon61bank Hi, welcome to OCA. please change your commit name to `[14.0][MIG] hr_employee_phone_extension`

**Comment by aphon61bank** [comment]
@tonygalmiche thank you.

**Review by fshah-initos — APPROVED** [review]
Code review and functional test Good

**Review by Saran440 — APPROVED** [review]
No change

**Pull request merged**
