### PR TITLE
remove addons depending on aeroo

### LINKED ISSUE #62: remove addons depending on aeroo reports
The following addons depend on aeroo report:
-    hr_payroll_register_report
-    hr_report_manpower
-    hr_report_payroll_attendance_summary
-    hr_report_payroll_net
-    hr_report_turnover

Aeroo reports is not an OCA module and the OCA policy is to not depend on 3rd party modules. 

In the discussion on OCA/reporting-engine/issues/1, the main author of aeroo reports strongly objected to the inclusion of his work in OCA. Since he also did not sign the CLA, I don't see how we could forcefully include his code in our code base. I therefore ask for the removal of the modules above.

If someone cares for these, it would be great if they could be cleanly moved elsewhere, and we will gladly provide a link in the README.md file pointing to that repository. If noone cares, I shall remove the modules from the git repository in a few weeks.

### PR DESCRIPTION
**Pull request by gurneyalex**
closes #62

### CODE REVIEW

**Comment by gurneyalex** [comment]
will need to merge this into 8.0 branch (once green and once #64 is merged)

**Comment by lepistone** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:

**Comment by joaoalf** [comment]
:+1:

**Pull request merged**
