### PR TITLE
[IMP] make our related fields nonstored

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't by default non-stored?

**Comment by hbrunn** [comment]
Weirdly enough, no. Or maybe not so weirdly: They are not new fields, but we make normal fields from hr related fields. At this stage, we end up with the store-flag being true.

**Comment by pedrobaeza** [comment]
OK, and why that strange way to define related instead of a string ("relational_field.sub_field")?

Anyway :+1:

**Comment by hbrunn** [comment]
@pedrobaeza actually, the list version is the more canonical one: https://github.com/OCA/OCB/blob/9.0/openerp/fields.py#L509

**Comment by pedrobaeza** [comment]
Oh, I see. Interesting to know that!

Is Travis error related?

**Comment by hbrunn** [comment]
yes, and I'm struggling to find out what goes wrong

**Comment by gurneyalex** [comment]
@hbrunn what's the status of this PR?

**Comment by hbrunn** [comment]
still no clue how to solve this to be honest

**Comment by hbrunn** [comment]
@gurneyalex now the status is green :-)

**Review by gurneyalex — APPROVED** [review]

**Review by moylop260 — APPROVED** [review]

**Pull request merged**
