### PR TITLE
[15.0][MIG] hr_org_chart_overview

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

- Add Constrain for prevent to assign manager recursively.
- Improve Organisation chart to have multiple root 

@ForgeFlow

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM, functional review.

**Comment by Saran440** [comment]
@JasminSForgeFlow please you update code again.

**Comment by nimarosa** [comment]
@JasminSForgeFlow Please rebase the PR.

**Comment by LoisRForgeFlow** [comment]
@Saran440 @nimarosa Rebase done!

**Pull request merged**
