### PR TITLE
[12.0][IMP] hr_expense_invoice

### PR DESCRIPTION
**Pull request by kittiu**
From expense sheet, add action "Create Invoice" from multiple expenses

### CODE REVIEW

**Comment by gustavovalverde** [comment]
I saw this odd behavior while creating an invoice from an expense; it won't allow me to save it:

image

**Review by gustavovalverde — APPROVED** [review]
Working as expected

**Comment by gustavovalverde** [comment]
@pedrobaeza this complies with the requirements talked in #615 

--

**Comment by andres-pcg** [comment]
Hello, i installed this module and i'm getting the following error when creating a report:

Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/odoo/odoo-server/src/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.actions.actions', <function IrActions.get_bindings at 0x7f6acacaa840>, frozenset({1, 2, 3, 4, 5, 6, 134, 8, 7, 12, 14, 15, 16, 18, 19, 20, 22, 23, 27, 28, 29, 30, 31, 32, 33, 34, 37, 38, 43, 47, 48, 53, 54, 58, 61, 62, 63, 64, 65, 76, 77, 78, 79, 80, 81, 82, 86, 87, 88, 89, 90, 91, 96, 97, 98, 99, 100, 102, 103, 104, 105, 106, 113, 114, 115, 117, 125, 126, 127}), 'hr.expense.sheet')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/odoo/odoo-server/src/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 1468, in fields_view_get
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
  File "<decorator-gen-36>", line 2, in get_bindings
  File "/odoo/odoo-server/src/odoo/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/models/ir_actions.py", line 122, in get_bindings
    result[binding_type].append(action.read()[0])
IndexError: list index out of range

**Comment by kittiu** [comment]
@andrp92 what report? Can you provide step to error?

**Comment by kittiu** [comment]
More test script added

**Comment by andres-pcg** [comment]
> @andrp92 what report? Can you provide step to error?
Sorry for the delay, i posted some pictures. 
JxL5xLfX7m
odoo server error

**Comment by kittiu** [comment]
We do not have such error.

Can you try with complete new database and just install this module.

Another thing is that we use CE. Can you try with CE and EE both.

**Comment by gustavovalverde** [comment]
This https://github.com/OCA/hr/pull/622#issuecomment-502391714 seems to be a problem when using it in EE

**Comment by gustavovalverde** [comment]
@pedrobaeza this not working in EE is a limitation for the PR to be merged? Maybe we can have a fix afterwards.

**Comment by pedrobaeza** [comment]
It's weird that the option can't be working for both EE and CE. Maybe this must be notified to odoo/odoo if discovered it's a bug. Please investigate first if it's something of current code.

**Comment by kittiu** [comment]
I can reproduce the error now, will try to fix. If you guys have any clue please let me know too. Thanks!

**Comment by gustavovalverde** [comment]
As far as I can see; the action was created differently as those in the core.

There's a change which add those binding_types; and as the action is defined in the code, odoo can't find this variable.

Background: https://github.com/odoo/odoo/commit/55549f1e612793769fc7bdf860ac6af06735a755

**Comment by kittiu** [comment]
I test the following steps to find this weird thing.

1. Create DB
2. Install hr_expense -> everything is OK
3. Install hr_expense_invoice
4. Go to Expense demo record and click Create Report --> Error
5. Go to Expense Report, nothing there yet, then create a dumb Expense Report record
6. Back to Expense demo record and click Create Report -> OK !

Then, I can go back to Expense Report and delete the dumb Expense Report record. And everything still works (even refresh screen, logout, etc).

To reproduce error again, I have to upgrade or remove and reinstall hr_expense_invoice.

It feels like, if we play around with Expense Report, something is loaded and it will be ok. :p

**Comment by gustavovalverde** [comment]
The issue is created by the action defined here: https://github.com/OCA/hr/blob/e3c525d2fbfdccb1f24edf872b101b4ae81b3b71/hr_expense_invoice/wizard/expense_create_invoice.xml 

If you remove that button it doesn't crash.

**Comment by kittiu** [comment]
@gustavovalverde I really can't find the solution yet. Your explanation make sense. If that's the case, it is core odoo bug?
> There's a change which add those binding_types; and as the action is defined in the code, odoo can't find this variable.

But I did test by making this https://github.com/odoo/odoo/blob/12.0/addons/hr_expense/models/hr_expense.py#L185
to call a valid XML action instead. Still got the same error.

**Comment by andres-pcg** [comment]
@kittiu, following @gustavovalverde advice, i created the action record this "

>     <record id="action_expense_create_invoice" model="ir.actions.act_window">
>         <field name="name">Create Invoice</field>
>         <field name="res_model">hr.expense.create.invoice</field>
>         <field name="src_model">hr.expense.sheet</field>
>         <field name="view_mode">form</field>
>         <field name="target">new</field>
>         <field name="binding_model_id" ref="hr_expense.model_hr_expense_sheet"/>
>     </record>

"  and did some test and it worked:

**Comment by kittiu** [comment]
@andrp92 it not work on mine. Have you try with clean database / new module install ?

**Comment by andres-pcg** [comment]
@kittiu tried new database and didn't work for me neither...

**Comment by andres-pcg** [comment]
@kittiu i found another bug, when you create an expense, approve it, and press the **create invoice** action, it wipes out the info from the **total_price** of the **expense_line_ids** field.

**Comment by kittiu** [comment]
@andrp92, thanks for noticing. This is a real problem with hr_expense_invoice @pedrobaeza @gustavovalverde 
Since the old hr_expense_invoice, it is build on the concept that, 1 invoice is created for 1 expense. And it is using the invoice.residual (invoice with open status) to update the expense amount directly. If user choose same invoice for multiple expense line, the amount in expense will already exceed amount on the invoice!

Now, with the new Action to create 1 invoice for multiple expense in hr.expense.sheet, the same problem is carried over.

TODO
1. To fix first the original problem with hr_expense_invoice, add a constraint in hr.expense.sheet so that no more than 1 expense is pointing to same invoice_id.
2. For new Action, when create 1 invoice for multiple selected expense, do not overwrite amount from invoice.residual back to expense line (the invoice is created by expense line amount anyway)

Problem I can see is,
* This leave 2 scenario contradict each other (user can confuse)

Actually, I think that the new action that we did is almost perfect for the real use case. Please discuss.

**Review by andres-pcg — CHANGES_REQUESTED** [review]
Hey @kittiu, while we discuss how we are going to address the problem you just mention (which is an interesting one 😄)  I found another bug, taxes are not being written on the invoice. 

[https://github.com/OCA/hr/blob/e3c525d2fbfdccb1f24edf872b101b4ae81b3b71/hr_expense_invoice/wizard/expense_create_invoice.py#L46](url)

To correct this i changed this code to: 
**'invoice_line_tax_ids': [(6, 0, x.tax_ids.ids)]})**

**Comment by kittiu** [comment]
@andrp92 Noted. Will apply it when we get final go.

**Comment by kittiu** [comment]
Any further comment before I start working on TODO?

**Comment by pedrobaeza** [comment]
I'm on holidays and I'm only doing minimal readings over the activity, so not being able to check in depth, so go ahead if you consider. Other fellow reviewers are here for checking :smiley:

**Comment by gustavovalverde** [comment]
@kittiu I was thinking on converting that 'Invoicing action' into a green button instead of an action in the middle of the form. Mainly because this is supposed to be part of the normal workflow, and final users are used to use those buttons instead of the middle action button.

**Comment by gustavovalverde** [comment]
I don't want to add more features to this PR; so I'll make another issue to discuss about adding the provider in expenses. As this will complete all the information needed to validate those invoices.

**Comment by kittiu** [comment]
> I'm on holidays and I'm only doing minimal readings over the activity, so not being able to check in depth, so go ahead if you consider. Other fellow reviewers are here for checking

@pedrobaeza have nice holidays :) my colleague addicted to Pedro's comment and asked me why you were quiet yesterday :D

**Comment by kittiu** [comment]
> I'm on holidays and I'm only doing minimal readings over the activity, so not being able to check in depth, so go ahead if you consider. Other fellow reviewers are here for checking

**Comment by kittiu** [comment]
@gustavovalverde +1 for the highlighted button instead of action menu to create invoice.

> so I'll make another issue to discuss about adding the provider in expenses

What you mean provider in expenses, are the new thing?

By the way, what is your opinion on the TODO: coz I think it need fixing in this PR too, is it not?

**Comment by kittiu** [comment]
@gustavovalverde @andrp92 @pedrobaeza 
I have made quite a bit of changes in the way things work (but still respect the original code)
https://github.com/OCA/hr/compare/e3c525d2fbfdccb1f24edf872b101b4ae81b3b71..511ae45314770c3c4f78f66f8e6cfae0a8246105
Basically, I think it should be more flexible and can work with multiple invoice in 1 expense reports.

I have not fix the test script yet, can you help test it, especially on account move, and whether it suit your needs.

**Comment by kittiu** [comment]
Note: I have not change the action to button yet. Will do it later after workflow is ok. Thanks.

**Comment by kittiu** [comment]
Hi again, we start using it and we come with more enhancement.

TODO: 
1. As invoice is created from new Create Invoice action, I want to hide Register Payment button from that invoice, to make sure people don't pay invoice by mistake.
2.  Our user mentioned that, as we can create invoice after expense approval, we should hide the invoice_id field on draft expense, as no one would create Open Invoice before expense anymore.
    * But to preserve the old functionality, may be we can do as configuration, user choose either way.

WDYT?

**Comment by pedrobaeza** [comment]
I wouldn't do that, but when button is clicked, raise an error if the invoice is linked to an reimbursable expense.

**Comment by kittiu** [comment]
> I wouldn't do that, but when button is clicked, raise an error if the invoice is linked to an reimbursable expense.

OK for (1)
What do you think about (2)

**Comment by pedrobaeza** [comment]
For 2, I think both cases are valid (link on draft or later). What is the problem to have it there?

**Comment by kittiu** [comment]
@pedrobaeza I can't object that it is also true. I will keep that open. For specific project, will just make that field invisible.
I will continue and complete this PR as discuss.

**Comment by kittiu** [comment]
This PR is ready to be reviewed/merged

**Comment by kittiu** [comment]
@gustavovalverde @andrp92
Any further comments on this PR. Is it workable for you?
@pedrobaeza

**Comment by kittiu** [comment]
@gustavovalverde @andrp92 @pedrobaeza :)

**Review by ps-tubtim — APPROVED** [review]

**Comment by kittiu** [comment]
@pedrobaeza can this be merged? If so, our team plan to migrate it to v13.
Note: it is being used for us to cover most of our used case perfectly now, and not in anyway remove the existing feature.

**Pull request merged**
