### PR TITLE
[12.0][MIG] hr_emergency_contact

### PR DESCRIPTION
**Pull request by robinkeunen**
Migration of `hr_emergency_contact`.

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]
LGTM :+1: Standard migration. Maybe we should change the name to `hr_employee_emergency_contact` but its not a problem for me to keep it like this.

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Comment by robinkeunen** [comment]
> LGTM 👍 Standard migration. Maybe we should change the name to `hr_employee_emergency_contact` but its not a problem for me to keep it like this.

Yep, it would be more consistent. I'll do that 👌

**Review by bealdav — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by robinkeunen** [comment]
@jarroyomorales I renamed the modules per your suggestion. Who can I ping for a merge?

**Comment by jarroyomorales** [comment]
@Saran440 @alexey-pelykh

**Pull request merged**
