### PR TITLE
[MIG] hr_attendance_reason: Migration to 13.0

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Comment by damdam-s** [comment]
cannot see runbot logs because log page leads to 404

**Comment by pedrobaeza** [comment]
Sometimes happen and the only solution is to rebuid until got it, sorry

**Comment by damdam-s** [comment]
@pedrobaeza ok no pb. thanks for quick answer

**Comment by damdam-s** [comment]
@pedrobaeza seems I cannot force rebuild by myself on runbot

**Comment by pedrobaeza** [comment]
Can you please move this to OCA/hr-attendance following #732?

**Comment by sergioliva7** [comment]
@damdam-s This should be moved to https://github.com/OCA/hr-attendance could you please do it? Thanks

**Comment by Saran440** [comment]
This module move on https://github.com/OCA/hr-attendance/pull/8

@damdam-s if you doing this pr. please tell me.

**Pull request closed without merging**
