### PR TITLE
Improve the readability and maintainability of the code.

### PR DESCRIPTION
**Pull request by pavelpy**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pavelpy this is a trivial change, any particular reason for making one?

**Review by jarroyomorales — APPROVED** [review]
It's not a big change, but if it helps reading the code and doesnt introduce any bugs LGTM

**Comment by alexey-pelykh** [comment]
@jarroyomorales absolutely, as long as CLA is in place as well

**Review by alexey-pelykh — CHANGES_REQUESTED** [review]
Please address the CLA issue

**Pull request closed without merging**
