### PR TITLE
[12.0][FIX] hr_expense_invoice: Update prices correctly after invoice creation from expense with some taxes defined

### PR DESCRIPTION
**Pull request by victoralmau**
Steps to reproduce:

- Create an expense with defined taxes.
- Create an expense sheet.
- Validate the expense sheet.
- Create an invoice from the expense with taxes.
- The amounts (unit amount and total amount) are not modified when the invoice is created.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT31447

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I don't get the patch, as both fields should have the same amount, which is the total. The operation should be:

- You introduce 100 € of unit price + 21% IVA. Total: 121 €
- Create invoice.
- On the expense, the unit price turns into 121 € and taxes are removed, so the total is still 121 €

Why this is not working with current code?

**Comment by victoralmau** [comment]
> I don't get the patch, as both fields should have the same amount, which is the total. The operation should be:
> 
>     * You introduce 100 € of unit price + 21% IVA. Total: 121 €
> 
>     * Create invoice.
> 
>     * On the expense, the unit price turns into 121 € and taxes are removed, so the total is still 121 €
> 
> 
> Why this is not working with current code?

Because although the taxes are left blank, defining the total amount of the invoice as the unit price of the expense auto-changes the total amount of the expense by increasing the taxes. 
This does NOT happen in v13 although it is the same code.

**Comment by pedrobaeza** [comment]
That can't be, so there's something incorrect, but this is definitively not the correct patch. Please dive more.

**Comment by victoralmau** [comment]
> That can't be, so there's something incorrect, but this is definitively not the correct patch. Please dive more.

Perfect, what do you think of my new proposal?

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Now this has more sense. Fast-tracking the patch:

/ocabot merge patch

**Pull request merged**
