### PR TITLE
6.1 language

### PR DESCRIPTION
**Pull request by bwrsandman**
Port of https://code.launchpad.net/~savoirfairelinux-openerp/openerp-hr/language/+merge/194925

### CODE REVIEW

**Comment by lepistone** [comment]
Hi @joaoalf @yvaucher @pedrobaeza Are the points you raised on launchpad still open? If not, we can probably merge that. Thanks!

**Comment by pedrobaeza** [comment]
Well, I still think we can find a way to not translate again all languages in this module, so I can't give my approval yet.

**Comment by yvaucher** [comment]
I'm ok with this first version. My remark was answered. :+1:

**Comment by ghost** [comment]
Is it really necessary to have 2 boolean fields for read and write. It seems redundant?

**Comment by bwrsandman** [comment]
@dufresnedavid You can have someone who can read and not write.

Do you mean it would be better as a selection?

**Comment by ghost** [comment]
I think it should be only one boolean named read/write and one boolean speak.

**Comment by max3903** [comment]
On my resume, I could say I read spanish, but I do not write it.

**Comment by yvaucher** [comment]
@dufresnedavid I disagree with you, reading is different than writing. As said @bwrsandman and @max3903 you can read a language and understand most of it but you couldn't write as you don't know enough rules of grammar or vocabulary. When reading you can make guess of meaning of some sentence or words in their context. You cannot guess when you are writing.

Moreover, if you take languages tests, you will be evalutated on listening, speaking, reading and writing skills. With a score on each skill.
http://en.wikipedia.org/wiki/International_English_Language_Testing_System#IELTS_test_structure

Still booleans seems to me a be too restrictive. However, as there are plenty of scales for languages, I wouldn't force to use one. In future we should replace it by a Selection list. Maybe with different modules for each type of scale.

**Comment by yvaucher** [comment]
@dufresnedavid @max3903 @pedrobaeza @bwrsandman @joaoalf If one of you also aprove I merge.

About @dufresnedavid remark, correct me if I'm wrong, but we have more opinion in favor of multiple booleans. So I consider it's ok that way.

**Comment by max3903** [comment]
:+1:

**Pull request merged**
