### PR TITLE
[14.0][MIG] hr_expense_portal : Migrated to 14.0

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@dreispt , @rafaelbn  and @max3903 , 

Can you please review this PR ?

**Comment by kittiu** [comment]
@AmmarOfficewalaSerpentCS 
From v13, v14, all hr-expense related module are moved to https://github.com/OCA/hr-expense

**Comment by AmmarOfficewalaSerpentCS** [comment]
@kittiu , 
Can you give me a step on how to take a v12 commit on anotherbranch?

**Comment by kittiu** [comment]
> @kittiu , Can you give me a step on how to take a v12 commit on anotherbranch?

From inside your hr-expense, add the remote reference to hr, i.e.,
```
git remote add oca-hr https://github.com/OCA/hr
```
Fetch it
```
git fetch oca-hr
```
Then pull it as you normally do, from oca-hr instead of origin.
```
git format-patch --keep-subject --stdout origin/14.0..oca-hr/12.0 -- hr_expense_portal | git am -3 --keep
```

Hope this help.

**Comment by AmmarOfficewalaSerpentCS** [comment]
Move this PR on the hr-expense module 

https://github.com/OCA/hr-expense/pull/70

**Pull request closed without merging**
