### PR TITLE
[MIG] hr_employee_lastnames: Migration to 15.0

### PR DESCRIPTION
**Pull request by luistorresm**

### CODE REVIEW

**Review by luiseevaquer — APPROVED** [review]
:+1:

**Comment by R4Alex** [comment]
LGTM! :+1:  +1

I made a few functional tests, the name of the employee is being formatted as expected in the three cases.

Screenshot from 2021-11-04 17-05-29
Screenshot from 2021-11-04 16-54-50
Screenshot from 2021-11-04 16-53-55
Screenshot from 2021-11-04 16-52-13

Also, the search is working as expected.

**Review by R4Alex — APPROVED** [review]

**Comment by luistorresm** [comment]
Hello @moylop260

Could you merge this MR if you agree, please?

Regards

**Pull request merged**
