### PR TITLE
[16.0][FWP][FIX] hr_employee_birthay_mail: res_users configurable

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
FWP of this FIX: https://github.com/OCA/hr/pull/1267

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Nice, ty!

**Comment by JoanSForgeFlow** [comment]
Hi,

Is it possible to merge this PR ?

Thank you

**Comment by JoanSForgeFlow** [comment]
@dreispt And also I think we can merge this.

Thank you

**Review by dreispt — APPROVED** [review]

**Pull request merged**
