### PR TITLE
[IMP] hr_job_category: Add tests and fix tag inheritance

### PR DESCRIPTION
**Pull request by etobella**
@leemannd This is what you were trying to achieve.... #1178

### CODE REVIEW

**Comment by leemannd** [comment]
Hello, this seems to aim for the same scope. Thank you for porting it to 14.0.

I hope you find someone to have it reviewed and merged

**Comment by etobella** [comment]
Well, your pr was failing... I was waiting for you to fix the test/code

**Review by leemannd — APPROVED** [review]

**Comment by leemannd** [comment]
Sorry for the miscommunication.

AFAIR: Early version of the fix where not failing. But it's too old.

Thank you a lot for thaking care of this :+1:

**Review by kluna1998 — APPROVED** [review]
LGTM! 👍🏽

**Pull request merged**
