### PR TITLE
[MIG] resource_hook: Migration to 14.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
Migrated into odoo addons (resource) (!)

### CODE REVIEW

**Review by MRomeera — APPROVED** [review]

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Comment by nimarosa** [comment]
Tested functionality. Rebase fails because permission errors. But it's a migration so we can merge. 

/ocabot migration resource_hook

**Comment by nimarosa** [comment]
This PR should be rebased and checked if we want to merge it. I can't rebase it with the bot

**Comment by chandni299** [comment]
Hello @etobella , what is the reason behind closing this PR? I would like to have this module in `14.0`.
Do we need to create PR once again for this?

**Comment by etobella** [comment]
We closed it as we did not need it anymore. Feel free to reopen it :smile:

**Comment by chandni299** [comment]
Hello @etobella, I do not have the right to reopen this PR. Could you please do it?
Thank you in advance!

**Comment by etobella** [comment]
You should take the same branch on your Repo and make the PR yourself. I will not fix any existing issues in this module, so it is necessary that someones creates a new PR

**Comment by chandni299** [comment]
Thank you @etobella :+1:  I will do it

**Pull request closed without merging**
