### PR TITLE
[WIP][ADD] hr_holidays_accrual_last_month_day: Allow force last month day.

### PR DESCRIPTION
**Pull request by luistorresm**
Allow force periodical accrual on last month day
Screen Shot 2020-04-29 at 20 23 29

### CODE REVIEW

**Comment by randall-vx** [comment]
:+1:

**Comment by alexey-pelykh** [comment]
Maybe it would be better to extend https://github.com/OCA/hr/tree/12.0/hr_holidays_accrual_advanced ?

**Comment by alexey-pelykh** [comment]
By adding `monthly` or `end_of_month` + `start_of_month` to https://github.com/OCA/hr/blob/12.0/hr_holidays_accrual_advanced/models/hr_leave_allocation.py#L108

**Comment by luistorresm** [comment]
Thanks @alexey-pelykh 

I move that to a new PR https://github.com/OCA/hr/pull/830, what do you think?

Regards

**Pull request closed without merging**
