### PR TITLE
[14.0][MIG] hr_personal_equipment_request

### PR DESCRIPTION
**Pull request by AntoniRomera**

### CODE REVIEW

**Comment by AntoniRomera** [comment]
@albariera @AaronHForgeFlow @etobella 
Can you review it?

The runbot is red but when you log in you can see that it is working fine, from the runbot it says that there are some alerts but not that it has failed.

**Review by albariera — COMMENTED** [review]
Functional review LGTM :) But could you change the name of the commit to "[MIG] hr_personal_equipment_request: Migration to 14.0" ?

**Comment by AntoniRomera** [comment]
> Functional review LGTM :) But could you change the name of the commit to "[MIG] hr_personal_equipment_request: Migration to 14.0" ?

I can change it but as a migration to 14 I haven't done anything but change the version, the commit is following the OCA guidelines, but I change the name without any problem.

**Comment by albariera** [comment]
Yes, you are right. I know the change is minimal, but I think is better to put the name indicating the migration to 14.0 because it will be more useful and easy to find in the commit history. Thank you!

**Review by albariera — APPROVED** [review]

**Review by etobella — APPROVED** [review]
LGTM :+1: Thanks for the migration :wink:

**Comment by AntoniRomera** [comment]
@pedrobaeza Can you merge?

**Comment by pedrobaeza** [comment]
I think that before merging this, it should be clarified in 13.0 such weird link with PPE.

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Comment by AntoniRomera** [comment]
@pedrobaeza @olgamarcocb 
Can we continue/merge with this RP, as the PPE issue is already solved?

**Comment by AntoniRomera** [comment]
@pedrobaeza 
I don't see it working, does it have to be re-launched?

**Pull request merged**
