### PR TITLE
[13.0][MIG] hr_experience

### PR DESCRIPTION
**Pull request by flachica**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
Please see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

**Comment by flachica** [comment]
> Please see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

Yes, I seeing it. I don't understand this comment. I made any error?

**Comment by alexey-pelykh** [comment]
You should've performed two separate commits - one for precommit reformatting, second one for actual migration

**Comment by flachica** [comment]
I close this PR. #809 is the last

**Pull request closed without merging**
