### PR TITLE
[13.0][MIG/IMP] hr_contract_currency

### PR DESCRIPTION
**Pull request by astirpe**
Porting hr_contract_currency to V13 + handling case company specified (or default company) and currency not specified

### CODE REVIEW

**Review by alexey-pelykh — CHANGES_REQUESTED** [review]
Please split migration and improvement into separate commits so we can backport improvement to v12

**Comment by astirpe** [comment]
It's already in two separate commits

**Comment by alexey-pelykh** [comment]
@astirpe thanks, for some reason yesterday it was a single commit, or my memory and eyes fail me :)

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM

**Review by Saran440 — APPROVED** [review]
Functional test. LGTM :+1:

**Comment by alexey-pelykh** [comment]
@astirpe would it be possible to backport improvement to v12?

**Pull request merged**
