### PR TITLE
[FIX] hr_employee_calendar_planning: link leaves

### PR DESCRIPTION
**Pull request by chienandalu**
- On the module init, existing employee calendar leaves should be linked
to the employee's new autocalendar.

cc @Tecnativa TT20229

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I didn't add the smart-button on purpose: that must be handled only in backend, not by user.

**Comment by chienandalu** [comment]
> I didn't add the smart-button on purpose: that must be handled only in backend, not by user.

I encountered some situations in wich the user would need to get rid of old calendars that could cause troubles, like the ones with lots of date_ranges on them, wich lead to multiple attendance_ids for the days issued.

Another use I think of is to leave on the user behalf to clean up the automatic calendars. When lots of them are present it can be quite a mess (when maybe just a handful of them could be really needed).

**Comment by pedrobaeza** [comment]
There's only one automatic calendar per employee. I insist this shouldn't be available at user level.

**Comment by chienandalu** [comment]
There's one atomatic calendar per user, but many calendars could be created in the module init to fit different date ranges or simply exist before and no be usable anymore.

**Comment by pedrobaeza** [comment]
> but many calendars could be created in the module init to fit different date ranges or simply exist before and no be usable anymore.

Yeah, but they are active=True, so no need to show the "Deactivate" button: remove them or adjust them.

**Comment by chienandalu** [comment]
Ok, I dropped the commit

**Review by pedrobaeza — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot merge minor

To be migrated to 11.0/12.0

**Pull request merged**
