### PR TITLE
Update split names at module install to get the value not the key of dict

### PR DESCRIPTION
**Pull request by feketemihai**
The same with #194 but moved to a new personal branch.

### CODE REVIEW

**Comment by feketemihai** [comment]
@dreispt Can you check this one too please...when you go on runbot all the employees have lastname firstname as the name...this should fix it...I push a rebuild on the runbot...

**Comment by feketemihai** [comment]
@dreispt Runbot is ready...

**Comment by dreispt** [comment]
LGTM :+1:
It would be nice to have a test added, though.

**Comment by feketemihai** [comment]
@dreispt Basically this is an update from https://github.com/OCA/hr/pull/190/files, the tests are there, only that the tests are not done at module install, so for create, write everythink is ok...only at install of the module i was not updated in 190...

**Comment by dreispt** [comment]
OK, I see. But that could still be tested:
If you have employee demo data you know to be there before the modules is installed, at the beginning of your tests you could check if the name transformation was done properly by the init scripts.

**Comment by feketemihai** [comment]
@dreispt I will added tomorow...

**Comment by gurneyalex** [comment]
:+1:

**Comment by moylop260** [comment]
:+1:

**Pull request merged**
