### PR TITLE
[14.0][MIG] hr_org_chart_overview :

### PR DESCRIPTION
**Pull request by irfani**
Add custom qweb template to properly show chart control toolbar

### CODE REVIEW

**Comment by irfani** [comment]
HR Org Chart in Odoo V14
image

**Comment by LoisRForgeFlow** [comment]
There is already a migration open for this module: https://github.com/OCA/hr/pull/941. Also you are not keeping commit history.

**Comment by irfani** [comment]
@LoisRForgeFlow ops sorry, so how to merge my pull request ?

**Comment by Saran440** [comment]
@irfani Do this PR start from PR #941?
if yes, you can rebase this PR into 1 commit.
then, I will cherry-pick from your PR to #941

**Pull request closed without merging**
