### PR TITLE
port module hr_contract_state for odoo v9

### PR DESCRIPTION
**Pull request by yweng8111**

### CODE REVIEW

**Comment by feketemihai** [comment]
@yweng8111 Thanks for the contribution, before review can you please fix travis errors...

**Comment by yweng8111** [comment]
@feketemihai There are some direct or indirect dependence between module hr_contract_state and hr_skill. So it can only be fixed if the commits of PR #299 is merged to the branch 9.0.

**Comment by yweng8111** [comment]
@feketemihai actually all the changes that I want to make was in PR #251, but @pedrobaeza said that I can only change one module in one PR :(

**Comment by feketemihai** [comment]
Please reopen the PR if it's important to you.

**Pull request closed without merging**
