### PR TITLE
[14.0][ADD] hr_department_code

### PR DESCRIPTION
**Pull request by Saran440**
Not sure that this module should be in this repo or repo `department`
- Add code in department
- Display [code] name. if not code it will display name
- Search filter name and code

Selection_001

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM

Here is fine, as there is a comment on departement:
`[DEPRECATED since 9.0] Odoo Department segregation and management `

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Comment by Saran440** [comment]
add order by code and name

**Comment by kittiu** [comment]
Ping @Saran440 can this merged?

**Pull request merged**
