### PR TITLE
[16.0][MIG] hr_emergency_contact: Migration to 16.0

### PR DESCRIPTION
**Pull request by jaenbox**
Standard migration to 16.0

### CODE REVIEW

**Comment by luistorresm** [comment]
Hello @jaenbox 

Could you squash the administrative commits?

https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

Regards

**Comment by jaenbox** [comment]
Hello @luistorresm, I have read the documentation but in this case I am not sure which commits I need to squash.

**Comment by luistorresm** [comment]
> Hello @luistorresm, I have read the documentation but in this case I am not sure which commits I need to squash.

Hello @jaenbox 

I see that:

- [UPD] Update hr_emergency_contact.pot
- Translated using Weblate (Portuguese (Brazil))

**Comment by jaenbox** [comment]
Hello @luistorresm,

I have squashed the "[UPD] Update hr_emergency_contact.pot" files. I haven't found any to squash with this "Translated using Weblate (Portuguese (Brazil))". Could you please kindly tell me exactly which ones I should use?

Regards

**Comment by luistorresm** [comment]
> Hello @luistorresm,
> 
> I have squashed the "[UPD] Update hr_emergency_contact.pot" files. I haven't found any to squash with this "Translated using Weblate (Portuguese (Brazil))". Could you please kindly tell me exactly which ones I should use?
> 
> Regards

Hello @jaenbox 

The next commit

https://github.com/OCA/hr/pull/1223/commits/eb588ffd6975c7e374b4b74e7f4762155bd053ca

must be squashed with [[15.0] MIG hr_emergency_contact:MIgration to 15.0](https://github.com/OCA/hr/pull/1223/commits/b016f25cfb0fc18ee716f732ec2d231b83109540)

Extra, I see that you add your user in the Contributors section.

With this migration is not necessary to add you as a contributor, 

Regards

**Comment by jaenbox** [comment]
> > Hello @luistorresm,
> > I have squashed the "[UPD] Update hr_emergency_contact.pot" files. I haven't found any to squash with this "Translated using Weblate (Portuguese (Brazil))". Could you please kindly tell me exactly which ones I should use?
> > Regards
> 
> Hello @jaenbox
> 
> The next commit
> 
> [eb588ff](https://github.com/OCA/hr/commit/eb588ffd6975c7e374b4b74e7f4762155bd053ca)
> 
> must be squashed with [[15.0] MIG hr_emergency_contact:MIgration to 15.0](https://github.com/OCA/hr/pull/1223/commits/b016f25cfb0fc18ee716f732ec2d231b83109540)
> 
> Extra, I see that you add your user in the Contributors section.
> 
> With this migration is not necessary to add you as a contributor,
> 
> Regards

I have made the indicated changes.

**Comment by luistorresm** [comment]
> > > Hello @luistorresm,
> > > I have squashed the "[UPD] Update hr_emergency_contact.pot" files. I haven't found any to squash with this "Translated using Weblate (Portuguese (Brazil))". Could you please kindly tell me exactly which ones I should use?
> > > Regards
> > 
> > 
> > Hello @jaenbox
> > The next commit
> > [eb588ff](https://github.com/OCA/hr/commit/eb588ffd6975c7e374b4b74e7f4762155bd053ca)
> > must be squashed with [[15.0] MIG hr_emergency_contact:MIgration to 15.0](https://github.com/OCA/hr/pull/1223/commits/b016f25cfb0fc18ee716f732ec2d231b83109540)
> > Extra, I see that you add your user in the Contributors section.
> > With this migration is not necessary to add you as a contributor,
> > Regards
> 
> I have made the indicated changes.

Hello @jaenbox 

Thanks.

Now I see that you added the bump version in the `[[IMP] hr_emergency_contact: pre-commit stuff](https://github.com/OCA/hr/pull/1223/commits/ae1781883aaacd11a496b639e2758f9111133c25)` commit.

Could you split it into 2 commits? Please

Regards

**Pull request closed without merging**
