### PR TITLE
[16.0][MIG] hr_contract_employee_calendar_planning

### PR DESCRIPTION
**Pull request by jonasbuchholz**
Migration to 16.0

### CODE REVIEW

**Review by luisDIXMIT — CHANGES_REQUESTED** [review]
Tested locally and it looks good to me! However, in the migration proccess code has been added, such as overwitten create method and modifications to hr.contract.history view, in addition to the already modified hr.contrat view. The overwritten create method should be tested in order to pass all checks. Can you add that test?

**Review by luisDIXMIT — APPROVED** [review]

**Comment by ChristophAbenthungCibex** [comment]
@pedrobaeza 
Can you merge it please? Or is there something left todo?

**Comment by pedrobaeza** [comment]
I don't use this module. @etobella should say. And each PR requires 2 approvals, and one from PSC:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
