### PR TITLE
Add spanish translations to oca-hr modules

### PR DESCRIPTION
**Pull request by nimarosa**
I translated some modules to spanish for my use, hope you find it useful.

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
> I translated some modules to spanish for my use, hope you find it useful.

Please use the weblate platform to do the translations.

https://odoo-community.org/page/translate

**Review by marcelsavegnago — CHANGES_REQUESTED** [review]
https://odoo-community.org/page/translate

**Comment by pedrobaeza** [comment]
Yes, please

**Comment by pedrobaeza** [comment]
Please also check the Spanish translation guide, not using upper case on the middle of sentences as well:

https://www.aeodoo.org/traduccion-de-odoo-al-espanol-de-espana

**Pull request closed without merging**
