### PR TITLE
[IMP] hr_attendance_report_theoretical_time: department record rule

### PR DESCRIPTION
**Pull request by chienandalu**
Department responsibles should be able to check their subordinates theoretical hours reports.

cc @Tecnativa TT38378

please review @victoralmau @pedrobaeza

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I don't think we should put this breaking change in a so old stable version, and more being about to migrate in our case. I think it's better to put in the instance.

**Comment by chienandalu** [comment]
Should we add it in v15 then?

**Comment by pedrobaeza** [comment]
We may evaluate it, but there are several possibilities, as you have the manager, but also the time off manager. Which one should be enabled? I think this is very specific to each company.

**Comment by chienandalu** [comment]
I see. Ok, let's leave it as a custom choice then

**Pull request closed without merging**
