### PR TITLE
[11.0][FIX] hr_employee_medical_examination: placeholder

### PR DESCRIPTION
**Pull request by jarroyomorales**
Minor fix to view placeholder. It can be fast-tracked @etobella @jbeficent @pedrobaeza

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM :+1: 
Just a question, as creator of the module, would you like to be the maintainer :smile:

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Please do a forward-port as well if applicable

**Comment by jarroyomorales** [comment]
@etobella Done!
@alexey-pelykh Can you merge again please? I think I canceled it attending @etobella 's comment

**Pull request closed without merging**
