### PR TITLE
[12.0][MIG] hr_employee_medical_examination

### PR DESCRIPTION
**Pull request by jarroyomorales**
Standard migration. no changes.

### CODE REVIEW

**Comment by Saran440** [comment]
@jarroyomorales Functional Test.
- Field year should be not show thousands separator.
- Tree view in menu View Medical Examinations should be show employee field for case create Medical Examinations from employee.

**Comment by jarroyomorales** [comment]
@Saran440 Attended you second comment. Regarding the first one, should I convert the field to char? The format is because of being an integer field, I dont know if there is an easy way to remove the formatting. Maybe its not that bad to keep it like this.

**Comment by Saran440** [comment]
@jarroyomorales IMO, if you used char field. It will look good and convert to integer when you want to calculate something in the future but I don't mind :)

**Review by Saran440 — APPROVED** [review]
Functional Test, LGTM :+1:

**Comment by jarroyomorales** [comment]
Okay, I put it as char @Saran440

**Review by etobella — APPROVED** [review]
LGTM

**Pull request merged**
