### PR TITLE
[9.0] [hr_period] migration to v9

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
@jbeficent  Could you please review?

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@darshan-serpent Please preserve the commit history from prior versions, as usual

**Comment by serpentcs-dev1** [comment]
@jbeficent How can I preserve the commits if the previous versions are not merged, right?



 [hr_period v8 PR](https://github.com/OCA/hr/pull/145)

**Comment by AaronHForgeFlow** [comment]
@darshan-serpent you can add  tarzan0820:8.0-hr_period as remote and work on top

**Comment by serpentcs-dev1** [comment]
#341 is the new PR for hr_period which preserves the commit.

**Pull request closed without merging**
