### PR TITLE
[12.0][ADD] hr_contract_rate: flexible wage

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Adds feature to specify contract amount not only as monthly wage, but also rate per various time period. There's a #604 PR for v11, yet it adds another depth level to contracts, while this PR uses vision that change of rate/wage should be accompanied by a new legal contract.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
cc @jarroyomorales since you're the author of #604

**Review by jarroyomorales — APPROVED** [review]
Tested and code review and LGTM, way better than `hr_contract_hourly_rate` module.
What do we do with it then? Should I close the PR and backport this or we keep the other module on 11 and start using this in 12.0?

**Comment by alexey-pelykh** [comment]
@jarroyomorales thanks for your review and feedback. If it's possible to make a migration script from `hr_contract_hourly_rate`  to `hr_contract_rate`, I'd go with backporting route, yet I don't really think it's worth it at all: the migration would have to flatten the "rate class" to contracts, yet that feels like "too much"?

**Comment by jarroyomorales** [comment]
Well, the problem its the same, creating a migration script from 10.0 to 11.0 or from 11.0 to 12.0 so I would go for the backporting too.
But yes, I also agree than it would be a heavy migration script for something very simple, maybe we can survive without it and users can migrate the important columns manually?

**Comment by alexey-pelykh** [comment]
I think this data migration should be part of OpenUpgrade then? Technically, it's "making a contract duplicate for every rate class in it", yet I think demand for that would be not that big.

**Comment by alexey-pelykh** [comment]
@jarroyomorales feels like backporting it is and let's deal with migration later

**Review by sweenya — APPROVED** [review]
Functional test

**Pull request merged**
