### PR TITLE
[16.0][MIG] hr_employee_digitized_signature: Migration to 16.0

### PR DESCRIPTION
**Pull request by jaenbox**
Standard migration to 16.0

### CODE REVIEW

**Review by nimarosa — APPROVED** [review]

**Review by Abranes — APPROVED** [review]

**Review by hieulucky111 — APPROVED** [review]
LGTM
Code review

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by nimarosa — APPROVED** [review]
Code review. Looks okay.

**Pull request merged**
