### PR TITLE
[12.0][FIX] hr_employee_service_contract: remove duplicate view

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@nikul-serpentcs @JagdishPanchalSCS if you don't mind, please review - you're aware of the topic already

**Comment by alexey-pelykh** [comment]
@pedrobaeza this one is a fix

**Review by pedrobaeza — APPROVED** [review]

**Review by nikul-serpentcs — APPROVED** [review]
LGTM :+1:

**Comment by alexey-pelykh** [comment]
@pedrobaeza please merge this one as well

**Pull request merged**
