### PR TITLE
[16.0][MIG] hr employee partner external

### PR DESCRIPTION
**Pull request by mymage**
Migration to 16.0

### CODE REVIEW

**Comment by luistorresm** [comment]
Hello @mymage 

Could you apply this point from the [Tasks to do in the migration](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#tasks-to-do-in-the-migration) 

`Squash administrative commits (if any) with the previous commit for reducing commit noise. They are named as "[UPD] README.rst", "[UPD] Update $MODULE.pot", "Update translation files" and similar names, and comes from OCA-git-bot, oca-travis or oca-transbot. IMPORTANT: Don't squash legit translation commits, authored by their translators, with the message "Translated using Weblate (...)".`

Regards

**Comment by mymage** [comment]
> Hello @mymage
> Could you apply ...

I did something, it's OK?

**Comment by luistorresm** [comment]
> > Hello @mymage
> > Could you apply ...
> 
> I did something, it's OK?

Yes @mymage 

Only was missing this commit:
[[UPD] Update hr_employee_partner_external.pot](https://github.com/OCA/hr/pull/1155/commits/1a3e0d0a45df0d91f5f1f599c2bb4c4ccfc52c7e)

Regards

**Review by nimarosa — APPROVED** [review]

**Review by luistorresm — APPROVED** [review]
Thanks @mymage

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
