### PR TITLE
[12.0] hr_attendance_report_theoretical_time: My Attendance as default

### PR DESCRIPTION
**Pull request by tschanzt**
Should make it nicer to use and make it faster if you can see a lot of employees.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I agree it's faster only with "My attendances", but not with "Current year". Imagine someone removes the filter "My attendances", on December and it's attendance officer. Then, all the attendances will be computed for the whole year for all employees. That's too much.

I prefer to keep the current month + previous month filter.

**Comment by tschanzt** [comment]
Thats true my description wasn't precise enough there. 
Its true that the computation will be too long if you remove the My Attendances filter, but it will be the same if someone removes both filters if we have current and previous month. (Although it might save you if you remove the filter by accident). But for most cases i think its more interesting to see the whole year.

**Comment by pedrobaeza** [comment]
As I put these filters in the original version, I still consider both as the best ones, but OK if you decide to change them. This is easily switchable to other through favorite put as default for all users.

**Comment by tschanzt** [comment]
We discussed it internally again and will customize the filters in the customer project. So this pr only adds the my attendance filter as a default.

**Review by pedrobaeza — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
This report is meant to be used normally by hr managers, isn't it?

**Comment by pedrobaeza** [comment]
It can be used by any employee with manual attendance.

**Review by AaronHForgeFlow — APPROVED** [review]
But normally it is used by the manager for reporting purposes, isn't it? Well, anyway it is not that costly to remove a filter so it is ok to me.

**Pull request merged**
