### PR TITLE
Merge 7.0 into 8.0

### PR DESCRIPTION
**Pull request by ghost**
Merge changes into 8.0 and move unmigrated modules to unported.

### CODE REVIEW

**Comment by dreispt** [comment]
"119 commits / showing with 14,475 additions and 374 deletions"
This is impossible to review.
Are these forward ports?

**Comment by ghost** [comment]
@dreispt Yes these are ports from 7.0

**Comment by ghost** [comment]
@max3903 @bwrsandman Reviews needed here.

**Comment by bwrsandman** [comment]
:-1: 

Not a huge fan of moving everything to `__unported__`. Use [`git filter-branch`](http://git-scm.com/docs/git-filter-branch) **at the time of porting of a module** to get the proper history. And for those unported, just add an issue to the bug tracker: `Port Module A from 7.0 to 8.0 ... Use this command ...`

https://github.com/odoomrp/odoomrp-wip/wiki/Migration-to-OCA

**Pull request closed without merging**
