### PR TITLE
[16.0][ADD] hr_employee_birthday_mail: birthday message and coworkers alert

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
The module automates the process of sending out personalized birthday emails to the celebrating employee while also informing their coworkers about the special day. It encourages a culture of mutual respect, camaraderie, and celebration within the team.

In essence, the 'hr_employee_birthday_mail' module ensures that every birthday is acknowledged and celebrated, thereby promoting a positive and unified work environment. 

@ForgeFlow

### CODE REVIEW

**Review by JasminSForgeFlow — APPROVED** [review]
Functional, LGTM!

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by MateuGForgeFlow — APPROVED** [review]

**Review by GuillemCForgeFlow — APPROVED** [review]
Functional review 👍🏽

**Review by nimarosa — APPROVED** [review]

**Comment by JoanSForgeFlow** [comment]
Sorry @nimarosa :pray: 
I just did a final push with minor changes. I think now the PR is ready to be merged!

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
@JoanSForgeFlow Yes no problem, i saw the PR approved and code looks okay so i merged. Merging again. 

/ocabot merge nobump

**Comment by JoanSForgeFlow** [comment]
weird, the tag is "Closed" and not "Merged" :thinking:

**Comment by nimarosa** [comment]
> weird, the tag is "Closed" and not "Merged" :thinking: 

Yes very weird. I don't know why the bot can close PRs, there is not command that closes PRs. Weird behavior.

**Pull request closed without merging**
