### PR TITLE
[10.0] [ADD] hr_period

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
HR Payroll Period
=================

Adds the concept of payroll period.

The objective is not to restrict or complicate the payroll workflow.
It is meant to reduce the number of clicks related to date selections and avoid mistakes.

Adds the date of payment on the payslip and payslip batch. This date is automatically filled when selecting
a period.

Adds a sequence on the payslip batch name and also adds the company on the payslip batch.

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Comment by AaronHForgeFlow** [comment]
Can you adapt this module to use the date_range module as base? Date range is a generic module for defining intervals: https://github.com/OCA/server-tools/tree/10.0/date_range

**Comment by nikul-serpentcs** [comment]
@aheficent adapted the date_range module.
Could you please review.
open PR for v9 #354

**Comment by AaronHForgeFlow** [comment]
Hi @nikul-serpentcs Can you include your commits on top of this?  https://github.com/OCA/hr/pull/354

**Comment by nikul-serpentcs** [comment]
I have preserved the commits [here](https://github.com/OCA/hr/pull/368), Closing this!

#368

**Pull request closed without merging**
