### PR TITLE
8.0 hr public holidays

### PR DESCRIPTION
**Pull request by saltonmassally**

### CODE REVIEW

**Comment by ghost** [comment]
@tarzan0820 thanks for working on this. I will review when I can.

**Comment by ghost** [comment]
@tarzan0820 please rebase on https://github.com/OCA/hr/pull/85. A lot of work has been done on it.

**Comment by saltonmassally** [comment]
@dufresnedavid  sure I can do that; I wished I had seen that PR before starting

**Comment by ghost** [comment]
@tarzan0820 thanks!

**Comment by saltonmassally** [comment]
@dufresnedavid @dreispt I tried rebasing of macopedia:public_holidays_8 and though i got the commits from there is came with million others... how can I fix this? Maybe it easier to just start a new PR since actual work has not started on this...

**Comment by ghost** [comment]
@tarzan0820 ok here is what you can do.
Copy your version of the module somewhere.
Then checkout on macopedia:public_holidays_8.
Rebase on OCA:8.0.
Get the diff with your version of the module and apply your changes.

**Comment by dreispt** [comment]
This should work, assuming `upstream` is the remote for OCA/hr:

```
git fetch upstream 8.0
git rebase FETCH_HEAD
```

**Pull request closed without merging**
