### PR TITLE
[12.0][FIX] hr_skill: fix permissions

### PR DESCRIPTION
**Pull request by alexey-pelykh**
image

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But why changing that names fix the problem?

**Comment by alexey-pelykh** [comment]
@pedrobaeza I have no idea but it works

**Comment by alexey-pelykh** [comment]
And I think you've mis-clicked on 11.0 milestone

**Review by pedrobaeza — APPROVED** [review]
This change seems harmless, but this is very weird.

**Comment by alexey-pelykh** [comment]
@max3903 @tarteo if possible, please review

**Review by max3903 — APPROVED** [review]

**Pull request closed without merging**
