### PR TITLE
[16.0][MIG] hr_personal_equipment_stock: Migration to 16.0

### PR DESCRIPTION
**Pull request by anusriNPS**
Migrating hr_personal_equipment_stock to 16.0

### CODE REVIEW

**Comment by anusriNPS** [comment]
Pickings are created when employee equipment request moves to "Accepted" state

Pickings_created_request_accept

However, the same scenario while executed as part of test case, pickings are not created when request moved to "Accepted" state

Testcase_issue

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Review by renda-dev — APPROVED** [review]
Code and functional review, LGTM

**Comment by renda-dev** [comment]
Greetings,
I personally think that this is quite helpful, could anyone please give this a look and maybe merge? 

@OCA/human-resources-maintainers

**Review by dreispt — APPROVED** [review]

**Pull request merged**
