### PR TITLE
[ADD] hr_employee_marital_status

### PR DESCRIPTION
**Pull request by hbrunn**
Marital status
==============

This module was written to replace the fixed selection in `Marital status` on employees by a configurable selection.

Configuration
=============

To configure this module, you need to:

#. go to `Human Resources/Settings/Marital statuses` to edit marital statuses

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review and tested on runbot :+1:

**Comment by feketemihai** [comment]
Hi @hbrunn, it is a good module, but my opinion that this should be a good improvement to hr_family, i think that we should try to compact the modules (this is basically only one fields with the init hook), that way we can maintain easier the repo...what do you think?

**Comment by hbrunn** [comment]
I agree, much better. #390 is from our company too, here the same applies. We'll probably update the PRs next week, I'll set a work in progress label meanwhile

**Comment by feketemihai** [comment]
@hbrunn Thanks for quick reaction..

**Comment by feketemihai** [comment]
@hbrunn Can we close this one, as it is included in #409 ?

**Comment by hbrunn** [comment]
sure

**Pull request closed without merging**
