### PR TITLE
[ADD] hr_course_survey

### PR DESCRIPTION
**Pull request by olgamarcocb**
This PR won't work until #1039 is merged.

### CODE REVIEW

**Comment by FernandoRomera** [comment]
@olgamarcocb 
Can you rensend?, the #1050 is closed and merge (it replace #1039).

**Comment by etobella** [comment]
Checking the function, this was added on this commit https://github.com/odoo/odoo/commit/d54a76d892571f54cbb1fdaa9c58483b5d4907d3
this was added on 2020 when odoo 13.0 was already released. However, the problem is related to an old odoo version.l

**Review by etobella — APPROVED** [review]

**Review by FernandoRomera — APPROVED** [review]

**Comment by FernandoRomera** [comment]
@OCA/human-resources-maintainers 
Can you merge this PR?

**Pull request merged**
