### PR TITLE
Add meta files

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It needs also a better repository description on README file. In this case, Travis informs about PEP8 errors.

**Comment by bwrsandman** [comment]
PEP8 fixes would be done in a following PR

**Comment by rvalyi** [comment]
:+1:  in favor of applying this before tackling further improvements

**Comment by pedrobaeza** [comment]
:+1:

**Comment by bwrsandman** [comment]
Damnit! I made the PR to the wrong branch!

**Pull request merged**
