### PR TITLE
[ADD][12.0] Added hr_expense_portal module.

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**

### CODE REVIEW

**Comment by rafaelbn** [comment]
Dear @AmmarOfficewalaSerpentCS ,

Thanks for this great contribution.

I'm trying to test int in runbot but it chrash with internal server error.

Could you please try fo test in in runbot?




Thanks

**Comment by AmmarOfficewalaSerpentCS** [comment]
#886

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
@rafaelbn I forced the Runbot rebuild and it is up now. Thanks!

**Comment by dreispt** [comment]
PS: -> https://runbot.odoo-community.org/runbot/build/3504892

**Pull request merged**
