### PR TITLE
13.0 mig hr holidays settings

### PR DESCRIPTION
**Pull request by meodoo**

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Review by astirpe — APPROVED** [review]

**Comment by emagdalenaC2i** [comment]
@pedrobaeza or @jbeficent this PR is approved, could you review it and merge?

**Comment by pedrobaeza** [comment]
@emagdalenaC2i I'm leaving my position in OCA board as community manager, so you should refrain from pinging me each time.

For now, I will launch /ocabot merge for this one.

**Comment by pedrobaeza** [comment]
It seems it doesn't work in the middle of a sentence:

/ocabot merge

**Comment by emagdalenaC2i** [comment]
Pedro, I'm sorry again but this time it's not my fault. It is really "your fault." ;-)

I know that I am pinging you seeeeveral times, but believe me, I always look for people related to the subject and then pinging them.

On this occasion I have looked for the people who have merged the last 10 PR in this repository and those are the two that I pinging

**Comment by pedrobaeza** [comment]
I know, that's why I'm telling you for knowing this. I'm still here across December. I have merged here because it complies with the rules of approvals and past days, but I'm only directly involved in a couple of PRs. Even when I'm out, I will continue my activity in OCA, but not being the wildcard for everything.

**Comment by emagdalenaC2i** [comment]
Ok, I'm sorry to hear that ... or not, maybe we're lucky and you can do other more important things ;-)
In any case, once again, thanks for all the work you do

**Pull request merged**
