### PR TITLE
[11.0][MIG] Backport of hr_employee_social_media from v12

### PR DESCRIPTION
**Pull request by jarroyomorales**
Standard migration

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@jarroyomorales would it be possible to add a test to v12 branch first and then do the porting?

**Review by alexey-pelykh — APPROVED** [review]
It would be great to get that test in v12 as well

**Review by alexey-pelykh — APPROVED** [review]

**Comment by jarroyomorales** [comment]
@Saran440 Can you check?

**Review by Saran440 — APPROVED** [review]
Code Review, LGTM :+1:

**Pull request merged**
