### PR TITLE
[12.0][Fix] Fix hr_attendance_report_theoretical_time pivot report

### PR DESCRIPTION
**Pull request by ghost**
This fixes an issue when printing the xls report of the pivot view from hr_attendance_report_theoretical_time

### CODE REVIEW

**Comment by jarroyomorales** [comment]
@busmanapps I have downloaded the pivot view as xls without this fix in version 12.0 and it has worked properly for me... Maybe it just fails in some cases. Anyways this doesn't do any bad but string should be `Theoretical vs Attended Time Analysis` instead of just `Attendances` in my opinion.

**Comment by busmanapps** [comment]
> @busmanapps I have downloaded the pivot view as xls without this fix in version 12.0 and it has worked properly for me... Maybe it just fails in some cases. Anyways this doesn't do any bad but string should be `Theoretical vs Attended Time Analysis` instead of just `Attendances` in my opinion.

In past versions it was "Attendances" that's why we put that, but yes I think "Theoretical vs Attendend Time Analysis" could be good too

**Comment by jarroyomorales** [comment]
@busmanapps Could you make the change? Thank you!

**Review by jarroyomorales — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Printing the XLS report? I don't get the problem...

**Pull request closed without merging**
