### PR TITLE
[16.0][ADD] hr_recruitment_torecruit

### PR DESCRIPTION
**Pull request by Murtaza-OSI**

### CODE REVIEW

**Comment by SMaciasOSI** [comment]
@Murtaza-OSI I adjusted the logic to the behaviour we are expecting. Please adjust the tests accordingly

**Comment by SMaciasOSI** [comment]
@max3903 This is ready to be merged

:+1:

**Comment by SMaciasOSI** [comment]
@max3903 Please review so we can merge

**Review by max3903 — APPROVED** [review]

**Pull request merged**
