### PR TITLE
[12.0] [ADD] hr_expense_type: new module

### PR DESCRIPTION
**Pull request by cubells**

### CODE REVIEW

**Review by rlizana — APPROVED** [review]
LGTM :+1:

**Review by MiguelPoyatos — APPROVED** [review]
LGTM!

**Comment by Saran440** [comment]
@cubells please, fix red travis (try pull code again)

**Comment by cubells** [comment]
@Saran440 done!

**Comment by cubells** [comment]
@Saran440 all is green now!

**Pull request merged**
