### PR TITLE
[IMP] add attribute name to page to improve the search in inheritance

### PR DESCRIPTION
**Pull request by mvasquez13**

### CODE REVIEW

**Comment by etobella** [comment]
Why do you change permissions?

**Comment by mvasquez13** [comment]
> Why do you change permissions?

Hi, because a person with a basic permission should not have access to this kind of personal information.

**Comment by etobella** [comment]
Well, the commit is referring to the change of the name page, not the permissions... Also, the permissions of the module allows all users to access this information. I think that you should split it in two PRs, as the change of permissions should be validated for more contributors than this.

**Review by astirpe — CHANGES_REQUESTED** [review]
@limfit changing the permissions the way you did (in the view) is not enough, since you can read those sensitive information in other ways, eg.: filtering, searches, etc...
Please only add the attribute name within this PR, as @etobella said. Thanks!

**Pull request closed without merging**
