### PR TITLE
[17.0][MIG] hr_personal_equipment_request : Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**

### CODE REVIEW

**Comment by peluko00** [comment]
Module migrated to version 17.0

cc https://github.com/APSL 148484

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

Issue https://github.com/OCA/hr/issues/1291

**Review by lbarry-apsl — APPROVED** [review]
Validated functionality

**Review by miquelalzanillas — APPROVED** [review]
Validated. Working.

**Comment by peluko00** [comment]
@pedrobaeza please review when you can

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration hr_personal_equipment_request
/ocabot merge nobump

**Pull request merged**
