### PR TITLE
[10.0][IMP] hr_employee_firstname: ease extension

### PR DESCRIPTION
**Pull request by luiseevaquer**
cherry-pick from
https://github.com/OCA/hr/pull/878/files

### CODE REVIEW

**Review by hugho-ad — APPROVED** [review]

**Comment by hugho-ad** [comment]
LGTM :+1: 

this is a cherry-pick from https://github.com/OCA/hr/pull/878/files

**Comment by moylop260** [comment]
/ocabot merge minor since that it is a approved change backported

**Comment by moylop260** [comment]
/ocabot merge patch since that it is a approved change backported

**Pull request merged**
