### PR TITLE
[PORT]Port hr_labour_union module to V8

### PR DESCRIPTION
**Pull request by ehdem**

### CODE REVIEW

**Comment by max3903** [comment]
The module is still in `__unported__` and you lost its history.

Please refer to https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8

**Comment by ehdem** [comment]
@max3903: I will do it

**Comment by feketemihai** [comment]
@ehdem Any update on this? Could you also remove translation files and refer to the latest module templates:
https://github.com/OCA/maintainer-tools/tree/master/template/module
Thanks.

**Comment by ghost** [comment]
@feketemihai we can trash this PR. @ehdem does not work on Odoo projects anymore.

**Pull request closed without merging**
