### PR TITLE
[16.0][MIG] hr_employee_service: Migration to 16.0

### PR DESCRIPTION
**Pull request by SoporteOperu**

### CODE REVIEW

**Comment by etobella** [comment]
You need to add mock on test-requirements.txt

**Comment by remi-filament** [comment]
Hi @SoporteOperu thank you for this PR,
could you please fix tests and cherry-pick #1221 ?

**Comment by michaelslade54** [comment]
Functional review OK.

**Comment by etobella** [comment]
@SoporteOperu Can you follow my comments please?

**Comment by remi-filament** [comment]
Hi @SoporteOperu do you plan to complete this PR or should someone take over the job to complete migration ?

**Comment by etobella** [comment]
@remi-filament I think someone need to take over this PR :cry:

**Comment by remi-filament** [comment]
Hi @etobella I just did here : #1330  (keeping existing commits from this PR)
Best Regards

**Pull request closed without merging**
