### PR TITLE
[ADD] hr_employee_benefit_on_job

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/OCA/hr/pull/82 must pass first

### CODE REVIEW

**Comment by ghost** [comment]
@bwrsandman

**Comment by mdietrichc2c** [comment]
LGTM :+1:

**Comment by charbeljc** [comment]
Waiting for travis, but LGTM :+1:

**Comment by ghost** [comment]
@bwrsandman I would like your review, than we can merge.

**Comment by bwrsandman** [comment]
LGTM :+1:

**Pull request merged**
