### PR TITLE
10.0 mig hr holidays validity date

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Comment by damdam-s** [comment]
cc @adrienpeiffer @gurneyalex

**Comment by adrienpeiffer** [comment]
@damdam-s the migration is already started here https://github.com/OCA/hr/pull/332

**Comment by damdam-s** [comment]
@adrienpeiffer no problems. I didn't checked :smile:

**Comment by adrienpeiffer** [comment]
@damdam-s Could you take a look on #332 ?

**Comment by feketemihai** [comment]
@damdam-s can you please update the code with small headers and to check the tests why it fails...

**Comment by damdam-s** [comment]
@feketemihai done :smile:

**Comment by damdam-s** [comment]
all :green_apple: :green_book: :green_heart:  !

**Review by feketemihai — APPROVED** [review]
Not tested...

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
