### PR TITLE
Remove list of deprecated modules, update readme.

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by feketemihai** [comment]
Follow up of #224

**Comment by ghost** [comment]
:+1:

**Comment by nhomar** [comment]
Hello.

IS this possible you can in the commit message explain why the modules is deprecated?

Deprecate a module without a single explanation (even if it is obvious) is a bad practice.

After a proper explanation of the deprecation +1 for me.

**Comment by dreispt** [comment]
I think we should have a separate PR for each module removed.
That allows to leave a better trail of why it was removed, and allows people interested in each particular module to present arguments on the corresponding discussion.

**Comment by feketemihai** [comment]
I will create separate PR with my opinion why it should be deprecate, i will create one PR for aeroo report removed in #63 from 7.0

**Pull request closed without merging**
