### PR TITLE
[14.0][BKP][MIG] hr_employee_birthday_mail

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
Backport of #1247 

@ForgeFlow

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by MiquelRForgeFlow — APPROVED** [review]
But I prefer BKP to BCK.

**Review by JaumeBforgeFlow — APPROVED** [review]
LGTM!

**Review by nimarosa — APPROVED** [review]

**Pull request merged**
