### PR TITLE
[ADD] hr_expense_sequence: Module for giving each expense a number

### PR DESCRIPTION
**Pull request by pedrobaeza**
# Sequence for HR expense

This module gives a unique number for each HR expense declaration.
# Configuration

You can change the default sequence (EX0000...) by the one of your choice
going to Settings > Technical > Sequences & Identifiers > Sequences, and
editing _HR expense_ record.

You will only have access to that section if your section has _Technical
features_ permission check marked.

### CODE REVIEW

**Comment by ghost** [comment]
Nice contribution. The post_init_hook is a good idea. As soon as pylint is fixed :+1:

**Comment by pedrobaeza** [comment]
Done

**Comment by pedrobaeza** [comment]
Can you please review this?

**Comment by lmignon** [comment]
:+1:  Thank you for the contrib @pedrobaeza

**Pull request merged**
