### PR TITLE
[16.0][MIG] hr_employee_service

### PR DESCRIPTION
**Pull request by mmarchpunt**

### CODE REVIEW

**Comment by nimarosa** [comment]
Please cherry pick this PR to the migration. 

https://github.com/OCA/hr/pull/1221

So the functionality is included en v16

**Comment by mmarchpunt** [comment]
@nimarosa done

**Review by nimarosa — APPROVED** [review]

**Review by remi-filament — CHANGES_REQUESTED** [review]
Hi @mmarchpunt thank your for this migration.
It seems there is already a PR opened for this migration : #1225  (though it does not include #1221).
Also, you did not preserve commit history from previous module which is not the expected way to migrate modules to new versions, since we would lose history, commiter names and we cannot easily compare what has really been modified in v16 (more info here : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0)

**Comment by mmarchpunt** [comment]
@remi-filament Thanks for your input, I will fix those issues

**Comment by mmarchpunt** [comment]
Closing PR

**Pull request closed without merging**
