### PR TITLE
[12.0][MIG] hr_worked_days_from_timesheet

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration from v10.

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Cannot enter payslip view. It fails: http://3391074-700-125b89.runbot3.odoo-community.org/web?debug=1#action=206&model=hr.payslip&view_type=list&menu_id=134

**Review by AaronHForgeFlow — APPROVED** [review]
Yeeeehaw :+1:  Working like a charm

**Review by nikul-serpentcs — APPROVED** [review]
Code Review LGTM :+1: 

Minor change: Add [README](https://github.com/OCA/maintainer-tools/tree/master/template/module/readme)

**Comment by meigallodixital** [comment]
Readme says branch 10 :)

**Comment by pedrobaeza** [comment]
It's regenerated on merge from readme folder and using proper branch.

**Comment by MiquelRForgeFlow** [comment]
Applied fragmented readme. I thought it was already applied.

**Comment by pedrobaeza** [comment]
Ouch! Then I must stop previous merge instruction.

**Pull request merged**
