### PR TITLE
[15.0] [MIG] hr_employee_age

### PR DESCRIPTION
**Pull request by pegonzalezspesol**
Work done:
- Migration version and functional test

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by marylla** [comment]
Hi @pegonzalezspesol Could you please rebase? Thank you :)

**Comment by pegonzalezs** [comment]
> Hi @pegonzalezspesol Could you please rebase? Thank you :)

rebased and all tests passing now.

regards

**Review by marylla — APPROVED** [review]
I made a functional review. Works as expected. :+1:

**Review by angelmoya — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
Techincal review LGTM

**Comment by marylla** [comment]
@pedrobaeza Can you merge this PR please? :)

**Pull request merged**
