### PR TITLE
[ADD] hr_employee_calendar_planning: Employee Calendar Planning

### PR DESCRIPTION
**Pull request by pedrobaeza**
This module allows to manage employee working time with profiles by date intervals.

The profiles are regular working time calendars, but they are treated as master ones here, allowing you to compose complexes working times by dates.

Under the hook, a unique working time is created for each employee with the proper composition for not affecting the rest of the functionality linked to this model.

Installation
============

During the installation of the module, current working times are split by start/end dates for having consistent data, and the potential new composed calendar planning is saved instead on the employee.

Configuration
=============

1. Go to *Employees > Employees*.
2. Open or create a new one.
3. On the "Public Information" page, fill the section "Calendar planning" with:

   * Starting date (optional).
   * Ending date (optional).
   * Working time to apply during that date interval.

Known issues / Roadmap
======================

* Add a wizard for generating next year calendar planning based on current one in batch.
* Add constraint for avoiding planning lines overlapping.
* Avoid the regeneration of whole private calendars each time a change is detected.

### CODE REVIEW

**Review by bjeficent — APPROVED** [review]
I tested the basic operations and it's okay. I was going to comment about the overlapping planning lines but it is already in the Roadmap section, so I'll not block the PR because of that. :+1:

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1:
Little UX issue I've found on runbot, 2 widgets are opened at same time.
image
Is it related with this PR??

**Comment by pedrobaeza** [comment]
@hveficent no, it isn't. Deactivate in your Chrome the auto-fill option.

**Review by jarroyomorales — APPROVED** [review]
LGTM :+1:

**Comment by nikul-serpentcs** [comment]
> Little UX issue I've found on runbot, 2 widgets are opened at same time.

@hveficent You can try in `incognito window or Firefox`

**Pull request merged**
