### PR TITLE
[16.0][MIG] hr_employee_age

### PR DESCRIPTION
**Pull request by destroT**

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Direct migration

**Comment by luistorresm** [comment]
Hello @destroT 

Please [Merge/squash the commits generated by bots or Weblate](https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate)

**Comment by destroT** [comment]
@luistorresm Is this okay or do I need to make other changes?

**Comment by luistorresm** [comment]
> @luistorresm Is this okay or do I need to make other changes?

Yes @destroT 

Only could you rename to commit message to `[MIG] hr_employee_age: Migration to 16.0`, please

**Comment by destroT** [comment]
> > Is this okay or do I need to make other changes?
> 
> Yes @destroT
> 
> Only could you

now should be fine

**Comment by luistorresm** [comment]
> > > Is this okay or do I need to make other changes?
> > 
> > 
> > Yes @destroT
> > Only could you
> 
> now should be fine

Hello @destroT 

I still see `[16.0][MIG] hr_employee_age`

**Comment by destroT** [comment]
> > > > Is this okay or do I need to make other changes?
> > > 
> > > 
> > > Yes @destroT
> > > Only could you
> > 
> > 
> > now should be fine
> 
> Hello @destroT
> 
> I still see `[16.0][MIG] hr_employee_age`

Hello @luistorresm,
I change it. I'm new and I don't understand why I need to change to `hr_employee_calendar_planning` since I'm migrating `hr_employee_age`, can you please explain it to me? 
thanks for the support

**Comment by luistorresm** [comment]
Hello @destroT 

Sorry, I fix the last message, the correct commit is "[MIG] hr_employee_age: Migration to 16.0"

But you are ok, only need to change the commit `[16.0][MIG] hr_employee_age` by `[MIG] hr_employee_age: Migration to 16.0`

You can see it on the [guidelines](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#how-to)

**Comment by destroT** [comment]
> Hello @destroT
> 
> Sorry, I fix the last message, the correct commit is "[MIG] hr_employee_age: Migration to 16.0"
> 
> But you are ok, only need to change the commit `[16.0][MIG] hr_employee_age` by `[MIG] hr_employee_age: Migration to 16.0`
> 
> You can see it on the [guidelines](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#how-to)

Finally it should be ok, thanks for the support

**Review by luistorresm — APPROVED** [review]

**Review by luistorresm — APPROVED** [review]

**Comment by nimarosa** [comment]
Merging. 

/ocabot merge nobump

**Pull request merged**
