### PR TITLE
[14.0][FIX] hr_employee_birthay_mail: res_users configurable

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
This PR allows each user to grant permission for anniversary notifications from "My profile", otherwise only HR administrators can edit it.

The group "hr.group_hr_user" is also added. Without this group, the open attendances at that time fail and do not allow the attendance session to be closed.

@ForgeFlow

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
LGTM 👍🏼

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Comment by JoanSForgeFlow** [comment]
@dreispt Is it possible to reopoen and merge? I think it is a needed fix for the module.

Thank you

**Comment by dreispt** [comment]
Sure, can you rebase please?

**Comment by JoanSForgeFlow** [comment]
@dreispt Yes, of course. Done!

**Review by dreispt — APPROVED** [review]

**Pull request merged**
