### PR TITLE
Move public holidays menu under Leaves menu.

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by astirpe** [comment]
I agree with this PR. Thank you @feketemihai 
:+1:

**Comment by jcdrubay** [comment]
+1

**Review by LeartS — APPROVED** [review]
Definitely agree, the current positioning in the "Employee" menu is quite weird.

**Review by pedrobaeza — APPROVED** [review]
A change in dependencies is not usually good, but as this is at the very beginning of the version cycle and it's very tight to the dependent module, I agree

**Comment by feketemihai** [comment]
@pedrobaeza I agree with you Pedro, but the thing is that it should depend in hr_holidays module, to align the menus...

**Comment by pedrobaeza** [comment]
OK, another reason more then!

**Pull request merged**
