### PR TITLE
[REM] Remove of hr_payroll_period module.

### PR DESCRIPTION
**Pull request by feketemihai**
Remove of hr_payroll_period module.

The module is not neccesary because of the new module hr_period in v7 which is ported on v8 on #145 .

@OCA/human-resources-maintainers

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by andhit-r** [comment]
:+1:

**Comment by dreispt** [comment]
It is unfortunate that two overlapping modules were allowed.
We should take more care so that it doesn't happen again.

**Comment by feketemihai** [comment]
@dreispt I agree on this (there was the hr_payroll_period module when the hr_period was merged, one year ago...)...but it happened so at least for v8 and v9 to maintain only one module...and since this one is in PR's for v8, it think it's better to release the other...

**Comment by ghost** [comment]
@dreispt also, just take a look at the code of hr_payroll_period. It's not maintainable at all.

**Pull request merged**
