### PR TITLE
[12.0][IMP] hr_expense_invoice: Migration transient m2m + Add button to invoice expense

### PR DESCRIPTION
**Pull request by victoralmau**
According to https://github.com/OCA/hr/issues/987 these PR added some functionalitty that exists now in 13.0 and allow to create invoice from expense.

Please @pedrobaeza and @joao-p-marques can you review it?

@Tecnativa TT29390

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@njeudy here you have the create invoice button by line.

**Review by pedrobaeza — APPROVED** [review]

**Review by joao-p-marques — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@njeudy do you want to review or do we proceed with the merge?

**Review by njeudy — APPROVED** [review]
Ok thanks for the work, it's ok for me now, and wizard is in expense now.

**Pull request merged**
