### PR TITLE
[14.0] [MIG] Migrating hr_contract_reference to v14.

### PR DESCRIPTION
**Pull request by square-ava**

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Comment by etobella** [comment]
hi, can you follow the standard migration method to keep the original commits please

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by square-ava** [comment]
Moved it to #976 then.

**Comment by etobella** [comment]
Close this then, but still, migration has not been kept on the new PR

**Pull request closed without merging**
