### PR TITLE
[MIG] hr_job_category: Migration to 15.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
Standard Migration

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Duplicate of :
- https://github.com/OCA/hr/pull/1118

**Review by ivantodorovich — APPROVED** [review]

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Working functional test. Merging this in favour of #1118 since the other PR don't resolve the issues. 

/ocabot merge nobump

**Pull request merged**
