### PR TITLE
[ADD] hr_payroll_total_ytd

### PR DESCRIPTION
**Pull request by bassn**
This module adds the year-to-date total on the payslip.
It is a fork:
- We fork module https://github.com/savoirfairelinux/odoo_payroll/tree/9.0/payroll_amount_ytd
- We upgrade it to Odoo 10.0
- We remove all dependencies and make it usable with Odoo core module hr_payroll
- This module sums up the field total while the forked module sums up the field amount

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I leave this PR opened, but please learn a bit more about GIT + GitHub before continue messing the repository. You need to respect commit history from the original Savoire-faire linux module. Use a similar technique like the one described here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by bassn** [comment]
Hello,

sorry, i now understand. 

I do not understand, why the build fails. Can someone support?

https://travis-ci.org/OCA/hr/builds/171868158

This module is not just a upgrade, it‘s a fork with feature changes (see readme)

Best regard

**Comment by pedrobaeza** [comment]
See the "stylistic" errors: https://travis-ci.org/OCA/hr/jobs/171851431#L309

I repeat: you need to respect commit history.

**Comment by bassn** [comment]
Sorry i already created PR 285. But i will not create a new one. ok.
The original savoir-faire linux module cannot work with odoo core module hr_payroll. It has a different goal. That why i forked it  (see readme file)

**Comment by andhit-r** [comment]
Hi @bassn thank for your contribution. Travis can be failed for numerous reasons. Please see travis log https://travis-ci.org/OCA/hr/builds/171851430 and try to fix it accordingly.

But before you fix travis i think you should:
1. Read OCA guidelines https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md
2. Read document on how to move move from one repo to oca repo like @pedrobaeza said. You have to respect original commit history.
3. Look into OCA's hr_payslip_ytd_amount https://github.com/OCA/hr/tree/7.0/hr_payslip_ytd_amount. Perhaps it already serve similar purpose. You just need to migrate it.

**Comment by bassn** [comment]
ok. thank. i understand.
But again the module hr_payslip_ytd_amount is different. It sums up the field amount while this new module sums up field total. Please read explanation in file README

**Comment by bassn** [comment]
travis log says:
     test_flake8                 FAIL
I do not understand that. Can someone explains what i have to do? Thanks.

**Comment by pedrobaeza** [comment]
You simply have to read what we have already said.

**Comment by andhit-r** [comment]
@bassn why don't you just add new field on hr_payslip_ytd_amount that sums field total. I think both field can be placed on one module. No need to add new module.

**Pull request closed without merging**
