### PR TITLE
[14.0][MIG] hr_employee_medical_examination

### PR DESCRIPTION
**Pull request by aphon61bank**
add access rules. and Change track_visibility are tracking, Ready for review.

### CODE REVIEW

**Comment by tonygalmiche** [comment]
I have this error with the wizard : 
image

**Comment by aphon61bank** [comment]
@tonygalmiche I have fix it. Thank you for review.

**Review by jarroyomorales — COMMENTED** [review]
Functional review LGTM!

Just some comments. In the medical examination form, the examination's name placeholder is `Employee's name`, which is kind of confusing, it could be 'Annual Revision' or something like this. 

Also there seems to be some conflicts with the translations, is this some problem of the translation bot or something needs to be done?

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Comment by kittiu** [comment]
Can you squash your commit? There should be only 2 commits. One is for pre-commit and another is your migration.

**Comment by aphon61bank** [comment]
@kittiu I'm edit finished,Thank you for review.

**Review by kittiu — APPROVED** [review]
Code review.

**Review by jarroyomorales — APPROVED** [review]

**Comment by kittiu** [comment]
This PR has pre-commit failed. Can you check again? @aphon61bank

**Comment by aphon61bank** [comment]
@kittiu I'm check finished.It's not failed.
Selection_012

**Comment by Saran440** [comment]
It's error because code is not update.
@aphon61bank Could you pull code again?

**Review by albariera — APPROVED** [review]
Functional review

**Comment by etobella** [comment]
@OCA/human-resources-maintainers I think we can proceed with merge

**Pull request merged**
