### PR TITLE
[7.0] Fix issue when no lastname is supplied

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by dreispt** [comment]
Why not this?

```
names = (vals.get('firstname'), vals.get('lastname'))
vals['name'] = " ".join(s for s in names if s)
```

**Comment by bwrsandman** [comment]
Because the error it fixes is in cases where `vals['name']` is supplied and first and last aren't.
I want to avoid overwriting vals['name']
see: https://travis-ci.org/OCA/hr/builds/30551570#L2047

**Comment by dreispt** [comment]
OK. :thumbsup:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
