### PR TITLE
[FIX] recalculate image_{small,medium} for partners

### PR DESCRIPTION
**Pull request by hbrunn**
without this, it looks like nothing happened for images because in the ui, we only see `image_medium`

### CODE REVIEW

**Comment by ghost** [comment]
@hbrunn Can you add unit tests for this module ?

**Comment by hbrunn** [comment]
@dufresnedavid usually, I'd gladly say 'yes', but this module doesn't really do anything interesting code wise. What would you suggest to test?

**Comment by ghost** [comment]
adjust_employee_partners_pre and adjust_employee_partners_post

I rather think that what they are very interesting codewise, since you use the cursor directly.

**Comment by hbrunn** [comment]
Those are init hooks. They will run anyways, adding a test won't increase code coverage I think?

**Comment by ghost** [comment]
Obviously, it will, since your PR decreases the coverage. Also, the coverage is one thing, but verifying that your code does what is expected from it is another.

**Comment by hbrunn** [comment]
@dufresnedavid now coveralls is happy

**Comment by ghost** [comment]
:+1: Thanks

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
