### PR TITLE
[15.0][MIG]hr_contract_employee_calendar_planning

### PR DESCRIPTION
**Pull request by jonasbuchholz**
Migration to 15.0

### CODE REVIEW

**Comment by Saran440** [comment]
@jonasbuchholz Hello,

Module migration must have old commit in PR. you can do it following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

**Review by yaseentai — APPROVED** [review]

**Review by dhx — APPROVED** [review]

**Comment by nimarosa** [comment]
@jonasbuchholz please keep commit history in migrations.

**Comment by jonasbuchholz** [comment]
@nimarosa Apologies, it seems that I missed a commit in this migration.

**Comment by nimarosa** [comment]
@jonasbuchholz No, I think you misunderstood. What me and @Saran440 are trying to say is that in a migration, you need to copy commit history from other versions and keep all the history. Here you are adding the module again in new commits. What you need to do is to copy all commit history from one branch to the other, and then make the standard migration commits on top of it. 

Please check the guide: 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

And also you can find useful the oca-port tool, search for it. It will help you automating the git commands to make a migration.

**Comment by jonasbuchholz** [comment]
Hi @nimarosa , thanks for the explanation. I did not apply new commits, I cherry-picked them from the 14.0 branch. However, I missed the automatically generated commits from the bot. With the command that is used in the guide you linked, this can be done in a single line, so thank you for showing that to me.
However, I do believe that the commit history is complete now.

**Comment by nimarosa** [comment]
@jonasbuchholz Sorry, I think you don't understand. 

You don't have to cherry pick anything. You just have to run exactly the commands in the guide in that order. You don't need to add files or copy them manually. If you follow the steps in the guide you will see that the module files will be copied form 14.0 to 15.0 automatically and commit history will he preserved. 

We should be able to see here all commits from the module first creating to now. Not only your commits. 

I suggest you create a new PR following the instructions in the guide or try with oca-port tool.

**Comment by jonasbuchholz** [comment]
@nimarosa I created the module in 14.0. Cherry-picking the individual commits will be the same as applying the format-patch. But if you prefer, I will open a new PR with these commits.

**Comment by nimarosa** [comment]
@jonasbuchholz but do you see the commit history here? I only see your commits. We need to preserve commit history of the module. That's the reason. You are no preserving the commits, you are adding new commits.

**Comment by jonasbuchholz** [comment]
@nimarosa I believe this is the entire commit history: https://github.com/OCA/hr/commits/14.0/hr_contract_employee_calendar_planning

**Comment by jonasbuchholz** [comment]
I'm the only one that ever contributed to this module thus far.

**Comment by nimarosa** [comment]
@jonasbuchholz Reopening. You are right. You know, i was confusing this module with [hr_employee_calendar_planning](https://github.com/OCA/hr/tree/14.0/hr_employee_calendar_planning) so i expected more commit history, but this is a new module introduced in 14.0 which you are the author. Sorry for my misunderstood.

**Review by nimarosa — APPROVED** [review]

**Pull request merged**
