### PR TITLE
[15.0][MIG]hr_recruitment_notification

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Comment by manuelregidor** [comment]
Included in core. Closing.

**Comment by pedrobaeza** [comment]
We put it on the roadmap...

**Comment by HaraldPanten** [comment]
> We put it on the roadmap...

Yep, we know. An internal misunderstanding 👍

**Comment by ValentinVinagre** [comment]
> > We put it on the roadmap...
> 
> Yep, we know. An internal misunderstanding +1

baia baia 👀

**Pull request closed without merging**
