### PR TITLE
[16.0][FIX] test refresh->invalidate_recordset

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Comment by FernandoRomera** [comment]
@nimarosa
Can you do a review and merge this FIX, please?. 
The same happens as in the "lastnames" module, but in the "firstname".

**Comment by nimarosa** [comment]
> @nimarosa
> 
> Can you do a review and merge this FIX, please?. 
> 
> The same happens as in the "lastnames" module, but in the "firstname".
> 
> 

@FernandoRomera  Please check runboat and we merge.

**Comment by FernandoRomera** [comment]
@nimarosa 
Do.

**Pull request merged**
