### PR TITLE
[MIG] 10.0 Porting hr_employee_reference

### PR DESCRIPTION
**Pull request by Yopli2k**

### CODE REVIEW

**Comment by leemannd** [comment]
@Yopli2k There is an open PR for this port https://github.com/OCA/hr/pull/316

**Comment by leemannd** [comment]
And for the trial_lenght https://github.com/OCA/hr/pull/305

**Comment by Yopli2k** [comment]
Ok, I'm sorry I did not see it. How can I cancel it?

**Comment by leemannd** [comment]
@Yopli2k If you want to participate, maybe you can do a small review on them. :)

**Pull request closed without merging**
