### PR TITLE
[12.0][FIX] hr_holidays_leave_auto_approve: post migration

### LINKED ISSUE #754: [12.0] hr_holidays_leave_auto_approve migrate(cr, installed_version)
When upgrading the module on Odoo.sh:

module hr_holidays_leave_auto_approve: Each post-migration file must have a "migrate(cr, installed_version)" function

@astirpe

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/hr/issues/754

### CODE REVIEW

**Comment by astirpe** [comment]
@CasVissers

**Review by CasVissers-360ERP — APPROVED** [review]
Tested and validated.

**Comment by jarroyomorales** [comment]
But will this work when migrating using OpenUpgrade?

**Comment by astirpe** [comment]
Yes

**Review by jarroyomorales — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Pull request merged**
