### PR TITLE
[14.0] [ADD] hr_employee_as_partner

### PR DESCRIPTION
**Pull request by paradoxxxzero**

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Comment by nimarosa** [comment]
Correct me if I'm wrong but in employee form the partner is created when you add the address fields, that are stored in partner model. So which is the use of this?

**Comment by paradoxxxzero** [comment]
The use case is to communicate with an employee (not a user) on a professional address (not on the private one).

**Review by PierrickBrun — APPROVED** [review]
LGTM

**Review by hieulucky111 — APPROVED** [review]
LGTM
Code Review

**Comment by hparfr** [comment]
@nimarosa  can we have this PR  merged ?

**Comment by nimarosa** [comment]
@hparfr Hello, I reopened the PR but you need to rebase it and also fix CI errors for this to be merged.

**Comment by hparfr** [comment]
@nimarosa 
rebased as requested

**Pull request closed without merging**
