### PR TITLE
[13.0][ADD] hr_personal_equipment_stock

### PR DESCRIPTION
**Pull request by albariera**
This module expands the functionality of the hr_personal_equipment request module proposed at #1026, allowing integration with stock.

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Nice module, just some minor things. First, if the route is move form another location I am getting an error in the procurement creation. This is the configuration of the route I used:


The error  is the following:
```
    result = method(recs, *args, **kwargs)
  File "/home/odoo/ForfeFlow/odoo/custom/src/hr/hr_personal_equipment_request/models/hr_personal_equipment_request.py", line 44, in accept_request
    rec.line_ids._accept_request()
  File "/home/odoo/ForfeFlow/odoo/custom/src/hr/hr_personal_equipment_stock/models/hr_personal_equipment.py", line 115, in _accept_request
    self._action_launch_procurement_rule()
  File "/home/odoo/ForfeFlow/odoo/custom/src/hr/hr_personal_equipment_stock/models/hr_personal_equipment.py", line 106, in _action_launch_procurement_rule
    self.env["procurement.group"].sudo().run([procurement])
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/addons/mrp/models/stock_rule.py", line 176, in run
    return super(ProcurementGroup, self).run(procurements_without_kit)
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/addons/stock/models/stock_rule.py", line 405, in run
    getattr(self.env['stock.rule'], '_run_%s' % action)(procurements)
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/addons/mrp/models/stock_rule.py", line 82, in _run_pull
    return super()._run_pull(procurements)
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/addons/stock/models/stock_rule.py", line 250, in _run_pull
    moves = self.env['stock.move'].sudo().with_context(force_company=company_id).create(moves_values)
  File "<decorator-gen-134>", line 2, in create
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/addons/stock/models/stock_move.py", line 440, in create
    res = super(StockMove, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/odoo/models.py", line 3817, in create
    records = self._create(data_list)
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/odoo/models.py", line 3923, in _create
    cr.execute(query, params)
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/ForfeFlow/odoo/custom/src/odoo/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: can't adapt type 'res.partner'
```

Also, maybe a smart button from the equipment request to the allocations would be nice. Do you agree?

And finally, do you think that having a button to scrap the products once they are used would be useful?

**Comment by albariera** [comment]
@AaronHForgeFlow Thanks for your review! The problem should be fixed now. 
I agree with you about the smart button, so I have added it at the base module at #1026.
About the scrap button, I do not think it is neccesary because when we give the personal equipment to an employee we alredy consider it as a scrap location. In some cases it can be returned, but I think it is not usual. In any case, it can always be marked as "expired"

**Review by etobella — APPROVED** [review]

**Review by FernandoRomera — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
