### PR TITLE
8.0 hr payroll run report xls

### PR DESCRIPTION
**Pull request by saltonmassally**

### CODE REVIEW

**Comment by saltonmassally** [comment]
@dreispt I have added "reporting-engine" to oca_dependencies but runbot is still failing... what am I not doing right? thanks

**Comment by gurneyalex** [comment]
@tarzan0820 can you rebase your PR?

**Comment by feketemihai** [comment]
@tarzan0820 @gurneyalex Do somebody from you continue work on this, do you still need it for v8, there are too many modules on v8, which we don't have a continuation for a long time, so if nobody wants to continue them i think we should close it.

**Comment by feketemihai** [comment]
Please reopen the PR if it's important to you.

**Pull request closed without merging**
