### PR TITLE
[12.0][MIG] hr_attendance_autoclose

### PR DESCRIPTION
**Pull request by ghost**
Done migrated.

### CODE REVIEW

**Comment by ghost** [comment]
Done migration, ready for review.

_**Note:**_ there is following error in ci/runbot, which is from other module **hr_employee_calendar_planning**
2019-06-05 03:39:39,533 171 WARNING openerp_test odoo.models: The model hr.employee.calendar has no _description

**Comment by ghost** [comment]
I made PR for the above mentioned problem here - https://github.com/OCA/hr/pull/612

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional tests

**Comment by kittiu** [comment]
Ghost is now back to @kittiu

**Comment by jarroyomorales** [comment]
Ghost, could you also add this hooks in the migration? If both PRs get merged 12.0 will not have the hooks.
https://github.com/OCA/hr/pull/627
Thank you!

**Comment by jarroyomorales** [comment]
@kittiu Will you work on this?

**Comment by kittiu** [comment]
Ok can. Sorry i miss fhe comment. I am on vacation will on when I am back.

**Comment by kittiu** [comment]
@kongrattapong please help continue with this #627

**Comment by kittiu** [comment]
@jarroyomorales done porting the new hook.
Sorry for much delayed.

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional test are good. But commit history seems not respected. Could you check?

**Review by jarroyomorales — APPROVED** [review]
@kittiu Thank you! Same comment as @aheficent , there is no commit history. But LGTM! :+1:

**Comment by kittiu** [comment]
Sorry, my mistake. Fixed.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  Great!

**Comment by AaronHForgeFlow** [comment]
There are two approvals bu those does not show on the reviewers section :confounded: 
image

**Comment by jarroyomorales** [comment]
@OCA/human-resources-maintainers can this be merged?

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by nikul-serpentcs — APPROVED** [review]
Code Review LGTM :+1:

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
