### PR TITLE
[17.0][MIG] hr_department_code: Migration to 17.0

### PR DESCRIPTION
**Pull request by RogerSans**
Internal task: T-6245
Standard migration

### CODE REVIEW

**Review by Tisho99 — APPROVED** [review]
LGTM! Functional and code review

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Comment by HaraldPanten** [comment]
@etobella @pedrobaeza 

Do you mind assigning this PR to the migration issue, and launch merge command, please?

THX

**Review by etobella — APPROVED** [review]

**Pull request merged**
